<?php
	class translations 
	{
		public static function create_translations() {
			return array(
				"all" => array(
					"sv" => "alla"
					,"en" => "all"
					)
				,"become a" => array(
					"sv" => "bli"
					,"en" => "become a"
					)
				,"by" => array(
					"sv" => "av"
					,"en" => "by"
					)
				,"currently the number of members is %d" => array(
					"sv" => "just nu är antalet medlemmar %d st"
					,"en" => "currently the number of members is"
					)
				,"hello" => array(
					"sv" => "hej"
					,"en" => "hello"
					)
				,"in" => array(
					"sv" => "i"
					,"en" => "in"
					)
				,"it needs at least three members to be activated" => array(
					"sv" => "för att bli aktiv måste den ha minst tre medlemmar"
					,"en" => "it needs at least three members to be activated"
					)
				,"its content has not yet been decided" => array(
					"sv" => "beslut om dess innehåll är ännu inte fattat"
					,"en" => "its content has not yet been decided"
					)
				,"last posts" => array(
					"sv" => "senaste inläggen"
					,"en" => "last posts"
					)
				,"me" => array(
					"sv" => "mig"
					,"en" => "me"
					)
				,"number of" => array(
					"sv" => "antal"
					,"en" => "number of"
					)
				,"sent" => array(
					"sv" => "skickat"
					,"en" => "sent"
					)
				,"superadmin" => array(
					"sv" => "superadmin"
					,"en" => "superadmin"
					)
				,"this is just a front page" => array(
					"sv" => "det här är bara en första-sida"
					,"en" => "this is just a front page"
					)
				,"this workgroup is proposed" => array(
					"sv" => "denna arbetsgrupp är föreslagen"
					,"en" => "this workgroup is proposed"
					)
				,"treasurer" => array(
					"sv" => "kassör"
					,"en" => "treasurer"
					)
				,"welcome" => array(
					"sv" => "välkommen"
					,"en" => "welcome"
					)
				,"you are a member of this" => array(
					"sv" => "du är medlem i denna"
					,"en" => "you are a member of this"
					)
				,"you have applied for membership in this" => array(
					"sv" => "du har ansökt om medlemskap i denna"
					,"en" => "you have applied for membership in this"
					)

				,"active:adj" => array(
					"sv" => "aktiv|t:a"
					,"en" => "active"
					)
				,"affirmed:adj" => array(
					"sv" => "beviljad|_t:e"
					,"en" => "affirmed"
					)
				,"my:adj" => array(
					"sv" => "min|_tt:a"
					,"en" => "my"
					)
				,"new:adj" => array(
					"sv" => "ny|tt:a"
					,"en" => "new"
					)
				,"old:adj" => array(
					"sv" => "gammal|t:___la"
					,"en" => "old"
					)

				,"active vote:noun1" => array(
					"sv" => "pågående omröstning:ar"
					,"en" => "active vote:s"
					)
				,"admin:noun1" => array(
					"sv" => "admin:istratörer"
					,"en" => "admin:istrators"
					)
				,"administrator:noun1" => array(
					"sv" => "administratör:er"
					,"en" => "administrator:s"
					)
				,"application:noun1" => array(
					"sv" => "ansökning:ar"
					,"en" => "application:s"
					)
				,"calendar:noun1" => array(
					"sv" => "kalender:__rar"
					,"en" => "calendar:s"
					)
				,"category:noun1" => array(
					"sv" => "kategori:er"
					,"en" => "category:_ies"
					)
				,"constituency:noun1" => array(
					"sv" => "valkrets:ar"
					,"en" => "constituency:_ies"
					)
				,"delegate:noun1" => array(
					"sv" => "delegat:er"
					,"en" => "delegate:s"
					)
				,"delegation:noun1" => array(
					"sv" => "delegering:ar"
					,"en" => "delegation:s"
					)
				,"description:noun1" => array(
					"sv" => "beskrivning:ar"
					,"en" => "description:s"
					)
				,"forum admin:noun1" => array(
					"sv" => "forumadministratör:er"
					,"en" => "forum admin:s"
					)
				,"inbox:noun1" => array(
					"sv" => "inbox:ar"
					,"en" => "inbox:es"
					)
				,"member:noun1" => array(
					"sv" => "medlem:mar"
					,"en" => "member:s"
					)
				,"member admin:noun1" => array(
					"sv" => "medlemsansvarig:a"
					,"en" => "member admin:s"
					)
				,"profile:noun1" => array(
					"sv" => "profil:er"
					,"en" => "profile:s"
					)
				,"outbox:noun1" => array(
					"sv" => "skickade"
					,"en" => "outbox"
					)
				,"proposition:noun1" => array(
					"sv" => "proposition:er"
					,"en" => "proposition:s"
					)
				,"setting:noun1" => array(
					"sv" => "inställning:ar"
					,"en" => "setting:s"
					)
				,"user:noun1" => array(
					"sv" => "användare"
					,"en" => "user:s"
					)
				,"vote:noun1" => array(
					"sv" => "omröstning:ar"
					,"en" => "vote:s"
					)
				,"vote admin:noun1" => array(
					"sv" => "valadministratör:er"
					,"en" => "vote admin:s"
					)
				,"workgroup:noun1" => array(
					"sv" => "arbetsgrupp:er"
					,"en" => "workgroup:s"
					)

				,"alternative:noun2" => array(
					"sv" => "alternativ"
					,"en" => "alternative:s"
					)
				,"forum:noun2" => array(
					"sv" => "forum"
					,"en" => "forum:s"
					)
				,"message:noun2" => array(
					"sv" => "meddelande:n"
					,"en" => "message:s"
					)
				,"password:noun2" => array(
					"sv" => "lösenord"
					,"en" => "password:s"
					)
				,"username:noun2" => array(
					"sv" => "användarnamn"
					,"en" => "username:s"
					)

				,"change:verb" => array(
					"sv" => "ändra"
					,"en" => "change"
					)
				,"create:verb" => array(
					"sv" => "skapa:(d|t:e)"
					,"en" => "create:d"
					)
				,"edit:verb" => array(
					"sv" => "redigera:(d|t:e)"
					,"en" => "edit:ed"
					)
				,"handle:verb" => array(
					"sv" => "hantera"
					,"en" => "handle"
					)
				,"list:verb" => array(
					"sv" => "lista"
					,"en" => "list"
					)
				,"login:verb" => array(
					"sv" => "logga in"
					,"en" => "login"
					)
				,"logout:verb" => array(
					"sv" => "logga ut"
					,"en" => "logout"
					)
				,"propose:verb" => array(
					"sv" => "föreslå:(_agen|_t:__na)"
					,"en" => "propose:d"
					)				
				,"remember:verb" => array(
					"sv" => "kom ihåg"
					,"en" => "remember"
					)				
				,"search:verb" => array(
					"sv" => "sök"
					,"en" => "search"
					)
				,"see:verb" => array(
					"sv" => "se"
					,"en" => "see"
					)
				,"view:verb" => array(
					"sv" => "visa"
					,"en" => "view"
					)
				,"write:verb" => array(
					"sv" => "skriv"
					,"en" => "write"
					)
			);
		}	
	} 
?>
