<?php
	class translations 
	{
		public static function create_translations() {
			return array(
				"Admin" => array(
					"sv" => "Admin"
					,"en" => "Admin"
					)
				,"Administrators" => array(
					"sv" => "Administratörer"
					,"en" => "Administrators"
					)
				,"Become a delegate" => array(
					"sv" => "Bli delegat"
					,"en" => "Become a delegate"
					)
				,"Calendar" => array(
					"sv" => "Kalender"
					,"en" => "Calendar"
					)
				,"Create new constituency" => array(
					"sv" => "Skapa ny valkrets"
					,"en" => "Create new constituency"
					)
				,"Create new vote" => array(
					"sv" => "Skapa ny omröstning"
					,"en" => "Create new vote"
					)
				,"Create new workgroup" => array(
					"sv" => "Skapa ny arbetsgrupp"
					,"en" => "Create new workgroup"
					)
				,"Create proposition" => array(
					"sv" => "Skapa proposition"
					,"en" => "Create proposition"
					)
				,"Delegates" => array(
					"sv" => "Delegater"
					,"en" => "Delegates"
					)
				,"Forum" => array(
					"sv" => "Forum"
					,"en" => "Forum"
					)
				,"Forum admin" => array(
					"sv" => "Forumadministratör"
					,"en" => "Forum admin"
					)
				,"Handle delegate" => array(
					"sv" => "Hantera delegat"
					,"en" => "Handle delegate"
					)
				,"Handle delegations" => array(
					"sv" => "Se delegeringar"
					,"en" => "Handle delegations"
					)
				,"Hello" => array(
					"sv" => "Hej"
					,"en" => "Hello"
					)
				,"Inbox" => array(
					"sv" => "Inbox"
					,"en" => "Inbox"
					)
				,"List active propositions" => array(
					"sv" => "Lista aktiva propositioner"
					,"en" => "List active propositions"
					)
				,"List active votes" => array(
					"sv" => "Lista pågående omröstningar"
					,"en" => "List active votes"
					)
				,"List affirmed propositions" => array(
					"sv" => "Lista beviljade propositioner"
					,"en" => "List affirmed propositions"
					)
				,"List constituencies" => array(
					"sv" => "Lista valkretsar"
					,"en" => "List constituencies"
					)
				,"List delegates" => array(
					"sv" => "Lista delegater"
					,"en" => "List delegates"
					)
				,"List old votes" => array(
					"sv" => "Lista gamla omröstningar"
					,"en" => "List old votes"
					)
				,"List votes" => array(
					"sv" => "Lista omröstningar"
					,"en" => "List votes"
					)
				,"Login" => array(
					"sv" => "Logga in"
					,"en" => "Login"
					)
				,"Logout" => array(
					"sv" => "Logga ut"
					,"en" => "Logout"
					)
				,"Member admin" => array(
					"sv" => "Medlemsansvarig"
					,"en" => "Member admin"
					)
				,"Members" => array(
					"sv" => "Medlemmar"
					,"en" => "Members"
					)
				,"Messages" => array(
					"sv" => "Meddelanden"
					,"en" => "Messages"
					)
				,"My profile" => array(
					"sv" => "Min profil"
					,"en" => "My profile"
					)
				,"New message" => array(
					"sv" => "Skriv meddelande"
					,"en" => "New message"
					)
				,"Outbox" => array(
					"sv" => "Skickade"
					,"en" => "Outbox"
					)
				,"Password" => array(
					"sv" => "Lösenord"
					,"en" => "Password"
					)
				,"Propositions" => array(
					"sv" => "Propositioner"
					,"en" => "Propositions"
					)
				,"Remember me" => array(
					"sv" => "Kom ihåg mig"
					,"en" => "Remember me"
					)
				,"Search" => array(
					"sv" => "Sök"
					,"en" => "Search"
					)
				,"Search propositions" => array(
					"sv" => "Sök propositioner"
					,"en" => "Search propositions"
					)
				,"Search votes" => array(
					"sv" => "Sök omröstningar"
					,"en" => "Search votes"
					)
				,"Search workgroup" => array(
					"sv" => "Sök arbetsgrupp"
					,"en" => "Search workgroup"
					)
				,"See proposed workgroups" => array(
					"sv" => "Se föreslagna arbetsgrupper"
					,"en" => "See proposed workgroups"
					)
				,"See workgroups" => array(
					"sv" => "Se arbetsgrupper"
					,"en" => "See workgroups"
					)
				,"Superadmin" => array(
					"sv" => "Superadmin"
					,"en" => "Superadmin"
					)
				,"Treasurer" => array(
					"sv" => "Kassör"
					,"en" => "Treasurer"
					)
				,"User" => array(
					"sv" => "Användare"
					,"en" => "User"
					)
				,"Username" => array(
					"sv" => "Användarnamn"
					,"en" => "Username"
					)
				,"Vote admin" => array(
					"sv" => "Valadministratör"
					,"en" => "Vote admin"
					)
				,"Votes" => array(
					"sv" => "Omröstningar"
					,"en" => "Votes"
					)
				,"Workgroups" => array(
					"sv" => "Arbetsgrupper"
					,"en" => "Workgroups"
					)
			);
		}	
	} 
?>
