<div id="dd-to-top">
	<a href="#pseudo_menubar" id="site-scroll-top" title="Gå till toppen av sidan" alt="Gå till toppen av sidan"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
</div>
<div id="footer">
	<footer>
		<div class="footer-widget">
        	<h2>Viktiga länkar</h2>
			<ul>
			<li>Länk</li>
			<li>Länk</li>
			<li>Länk</li>
			</ul>
        </div>
        <div class="footer-widget">
        	<h2>Meny</h2>
			<ul>
			<li class="f-member"><a href="index.php?type=member">Användare</a></li>
			<li class="f-message"><a href="index.php?type=message">Meddelanden</a></li>
			<li class="f-votes"><a href="index.php?type=vote">Omröstningar</a></li>
			<li class="f-forum"><a href="index.php?type=forum">Forum</a></li>
			<li class="f-admin"><a href="index.php?type=member&action=view&id=5#">Admin</a></li>
			</ul>
        </div>
        <div class="footer-widget">
        	<h2>Logga ut</h2>
			<ul>
			<li><a href="index.php?logout=1">Logga ut</a></li>
			</ul>
			<h2>Sociala media</h2>
			<ul>
			<li><a href="https://www.facebook.com/direktdemokraterna" target="_blank" alt="Besök vår Facebooksida" title="Besök vår Facebooksida">Facebook</li>
			<li><a href="https://twitter.com/DDemokraterna" target="_blank" alt="Besök vår Twitter" title="Besök vår Twitter">Twitter</li>
			<li><a href="https://plus.google.com/+Direktdemokraterna/posts" target="_blank" alt="Besök vår Google Plus-sida" title="Besök vår Google Plus-sida">Google Plus</li>
			<li><a href="http://youtube.com/Direktdemokraterna" target="_blank" alt="Besök vår Youtube-kanal" title="Besök vår Youtube-kanal">Youtube</li>
			</ul>
        </div>
        <div class="footer-widget">
        	<h2>Sök i forumen</h2>
			<ul>
			<li>Länk</li>
			<li>Länk</li>
			<li>Länk</li>
			</ul>
        </div>
	</footer>
</div>
