<?php
namespace Thesaurus; 

class adverbs 
{
	public static function create_translations() {
		return array(
			"after:adverb" => array(
				"sv" => "efter att"
				,"en" => "after"
				)
			,"after half:adverb" => array(
				"sv" => "efter halva"
				,"en" => "after half"
				)
			,"again:adverb" => array(
				"sv" => "igen"
				,"en" => "again"
				)
			,"already:adverb" => array(
				"sv" => "redan"
				,"en" => "already"
				)
			,"also:adverb" => array(
				"sv" => "också"
				,"en" => "also"
				)
			,"back:adverb" => array(
				"sv" => "tillbaka"
				,"en" => "back"
				)
			,"completely:adverb" => array(
				"sv" => "fullständigt"
				,"en" => "completely"
				)
			,"currently:adverb" => array(
				"sv" => "för närvarande"
				,"en" => "currently"
				)
			,"even:adverb" => array(
				"sv" => "även"
				,"en" => "even"
				)
			,"here:adverb" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"just:adverb" => array(
				"sv" => "bara"
				,"en" => "just"
				)
			,"no longer:adverb" => array(
				"sv" => "inte längre"
				,"en" => "no longer"
				)
			,"not:adverb" => array(
				"sv" => "inte"
				,"en" => "not"
				)
			,"not yet:adverb" => array(
				"sv" => "ännu inte"
				,"en" => "not yet"
				)
			,"now:adverb" => array(
				"sv" => "nu"
				,"en" => "now"
				)
			,"other than:adverb" => array(
				"sv" => "annat än"
				,"en" => "other than"
				)
			,"only:adverb" => array(
				"sv" => "bara"
				,"en" => "only"
				)
			,"personally:adverb" => array(
				"sv" => "personligt"
				,"en" => "personally"
				)
			,"[pron]still:adverb" => array(
				"sv" => "ändå"
				,"en" => "still"
				)
			,"still:adverb" => array(
				"sv" => "fortfarande"
				,"en" => "still"
				)
			,"temporarily:adverb" => array(
				"sv" => "tillfälligt"
				,"en" => "temporarily"
				)
			,"together:adverb" => array(
				"sv" => "tillsammans"
				,"en" => "together"
				)
			,"too:adverb" => array(
				"sv" => "för"
				,"en" => "too"
				)
			,"wrong:adverb" => array(
				"sv" => "fel"
				,"en" => "wrong"
				)
			,"why:adverb" => array(
				"sv" => "varför"
				,"en" => "why"
				)
		);
	}	
} 
?>
