<?php
namespace Thesaurus; 

class adverbs 
{
	public static function create_translations() {
		return array(
			"again:adverb" => array(
				"sv" => "igen"
				,"en" => "again"
				)
			,"already:adverb" => array(
				"sv" => "redan"
				,"en" => "already"
				)
			,"back:adverb" => array(
				"sv" => "tillbaka"
				,"en" => "back"
				)
			,"here:adverb" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"just:adverb" => array(
				"sv" => "bara"
				,"en" => "just"
				)
			,"no longer:adverb" => array(
				"sv" => "inte längre"
				,"en" => "no longer"
				)
			,"not:adverb" => array(
				"sv" => "inte"
				,"en" => "not"
				)
			,"not yet:adverb" => array(
				"sv" => "ännu inte"
				,"en" => "not yet"
				)
			,"now:adverb" => array(
				"sv" => "nu"
				,"en" => "now"
				)
			,"personally:adverb" => array(
				"sv" => "personligt"
				,"en" => "personally"
				)
			,"still:adverb" => array(
				"sv" => "fortfarande"
				,"en" => "still"
				)
			,"temporarily:adverb" => array(
				"sv" => "tillfälligt"
				,"en" => "temporarily"
				)
			,"too:adverb" => array(
				"sv" => "för"
				,"en" => "too"
				)
			,"wrong:adverb" => array(
				"sv" => "fel"
				,"en" => "wrong"
				)
			,"why:adverb" => array(
				"sv" => "varför"
				,"en" => "why"
				)
		);
	}	
} 
?>
