<?php
namespace Thesaurus; 

class adverbs 
{
	public static function create_translations() {
		return array(
			"back:adverb" => array(
				"sv" => "tillbaka"
				,"en" => "back"
				)
			,"here:adverb" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"not:adverb" => array(
				"sv" => "inte"
				,"en" => "not"
				)
			,"temporarily:adverb" => array(
				"sv" => "tillfälligt"
				,"en" => "temporarily"
				)
			,"wrong:adverb" => array(
				"sv" => "fel"
				,"en" => "wrong"
				)
		);
	}	
} 
?>
