<?php
namespace Thesaurus; 

class conjunctions 
{
	public static function create_translations() {
		return array(
			"and:conj" => array(
				"sv" => "och"
				,"en" => "and"
				)
			,"both:conj" => array(
				"sv" => "både"
				,"en" => "both"
				)
			,"if:conj" => array(
				"sv" => "om"
				,"en" => "if"
				)
			,"or:conj" => array(
				"sv" => "eller"
				,"en" => "or"
				)
		);
	}	
} 
?>
