<?php
namespace Thesaurus; 

class conjunctions 
{
	public static function create_translations() {
		return array(
			"and:conj" => array(
				"sv" => "och"
				,"en" => "and"
				)
			,"both:conj" => array(
				"sv" => "både"
				,"en" => "both"
				)
			,"in case:conj" => array(
				"sv" => "ifall"
				,"en" => "in case"
				)
			,"if:conj" => array(
				"sv" => "om"
				,"en" => "if"
				)
			,"or:conj" => array(
				"sv" => "eller"
				,"en" => "or"
				)
			,"so:conj" => array(
				"sv" => "så"
				,"en" => "so"
				)
			,"that:conj" => array(
				"sv" => "att"
				,"en" => "that"
				)
			,"until:conj" => array(
				"sv" => "tills"
				,"en" => "until"
				)
			,"when:conj" => array(
				"sv" => "när"
				,"en" => "when"
				)
		);
	}	
} 
?>
