<?php
namespace Thesaurus; 

class interjections 
{
	public static function create_translations() {
		return array(
			"hello:interjection" => array(
				"sv" => "hej"
				,"en" => "hello"
				)
			,"no:interjection[]" => array(
				"sv" => "nej"
				,"en" => "no"
				)
			,"welcome:interjection" => array(
				"sv" => "välkommen"
				,"en" => "welcome"
				)
			,"yes:interjection" => array(
				"sv" => "ja"
				,"en" => "yes"
				)
		);
	}	
} 
?>
