<?php
namespace Thesaurus; 

class new_phrases 
{
	public static function create_translations() {
		return array(
			"[]candidate in" => array(
				"sv" => "kandidat in"
				,"en" => "candidate in"
				)
			,"last login" => array(
				"sv" => "senast inloggad"
				,"en" => "last login"
				)
			,"reply to" => array(
				"sv" => "svar till"
				,"en" => "reply to"
				)
			,"vote status" => array(
				"sv" => "Omröstningens status"
				,"en" => "vote status"
				)
		);
	}	
} 
?>
