<?php
namespace Thesaurus; 

class nouns 
{
	public static function create_translations() {
		return array(
			//singular_indefinite:plural_indefinite:singular_definite:plural_definite
			"access:noun1" => array(
				"sv" => "tillgång"
				,"en" => "access"
				)
			,"active vote:noun1" => array(
				"sv" => "pågående omröstning:ar"
				,"en" => "active vote:s"
				)
			,"activity:noun1" => array(
				"sv" => "aktivitet"
				,"en" => "activity"
				)
			,"address:noun1" => array(
				"sv" => "adress:er:en:na"
				,"en" => "address:es"
				)
			,"admin:noun1" => array(
				"sv" => "admin:istratörer"
				,"en" => "admin:istrators"
				)
			,"administrator:noun1" => array(
				"sv" => "administratör:er:-s"
				,"en" => "administrator:s"
				)
			,"application:noun1" => array(
				"sv" => "ansökning:ar"
				,"en" => "application:s"
				)
			,"authorisation:noun1" => array(
				"sv" => "behörighet:er"
				,"en" => "authorisation:s"
				)
			,"ballot:noun1" => array(
				"sv" => "röst:er:en:na"
				,"en" => "ballot:s"
				)
			,"bold:noun1" => array(
				"sv" => "fetstil"
				,"en" => "bold"
				)
			,"[]bold:noun1" => array(
				"sv" => "fet"
				,"en" => "bold"
				)
			,"box:noun1" => array(
				"sv" => "ruta:_or:n:na"
				,"en" => "box:es"
				)
			,"budget:noun1" => array(
				"sv" => "budget:ar:-"
				,"en" => "budget:s"
				)
			,"button:noun1" => array(
				"sv" => "knapp:ar:en:na"
				,"en" => "button:s"
				)
			,"calendar:noun1" => array(
				"sv" => "kalender:__rar"
				,"en" => "calendar:s"
				)
			,"candidacy:noun1" => array(
				"sv" => "kandidatur:er:en:na:-"
				,"en" => "candidacy:_ies"
				)
			,"candidate:noun1" => array(
				"sv" => "kandidat:er:en:na:-"
				,"en" => "candidate:s"
				)
			,"caption:noun1" => array(
				"sv" => "rubrik:er:en:na"
				,"en" => "caption:s"
				)
			,"category:noun1" => array(
				"sv" => "kategori:er"
				,"en" => "category:_ies"
				)
			,"change:noun1" => array(
				"sv" => "förändring:ar"
				,"en" => "change:s"
				)
			,"city:noun1" => array(
				"sv" => "postort"
				,"en" => "city"
				)
			,"constituency:noun1" => array(
				"sv" => "valkrets:ar:en:na:-"
				,"en" => "constituency:_ies"
				)
			,"database:noun1" => array(
				"sv" => "databas:-"
				,"en" => "database"
				)
			,"day:noun1" => array(
				"sv" => "dag:ar:en:na"
				,"en" => "day:s"
				)
			,"debate:noun1" => array(
				"sv" => "debatt:er"
				,"en" => "debate:s"
				)
			,"delegate:noun1" => array(
				"sv" => "delegat:er:-"
				,"en" => "delegate:s"
				)
			,"delegate's:noun1" => array(
				"sv" => "delegats"
				,"en" => "delegate's"
				)
			,"delegate setting:noun1" => array(
				"sv" => "delegatinställning:ar"
				,"en" => "delegate setting:s"
				)
			,"delegation:noun1" => array(
				"sv" => "delegering:ar"
				,"en" => "delegation:s"
				)
			,"description:noun1" => array(
				"sv" => "beskrivning:ar"
				,"en" => "description:s"
				)
			,"email:noun1" => array(
				"sv" => "e-post:-"
				,"en" => "email"
				)
			,"exclusion:noun1" => array(
				"sv" => "uteslutning"
				,"en" => "exclusion"
				)
			,"filtering:noun1" => array(
				"sv" => "filtrering"
				,"en" => "filtering"
				)
			,"forum admin:noun1" => array(
				"sv" => "forumadministratör:er"
				,"en" => "forum admin:s"
				)
			,"front page:noun1" => array(
				"sv" => "första-sida"
				,"en" => "front page"
				)
			,"group:noun1" => array(
				"sv" => "grupp:er:-"
				,"en" => "group:s"
				)
			,"hit:noun1" => array(
				"sv" => "träff:ar"
				,"en" => "hit:s"
				)
			,"image:noun1" => array(
				"sv" => "bild:er:en:na"
				,"en" => "image:s"
				)
			,"inbox:noun1" => array(
				"sv" => "inkorgen"
				,"en" => "inbox"
				)
			,"individual:noun1" => array(
				"sv" => "privatperson"
				,"en" => "individual"
				)
			,"italic:noun1" => array(
				"sv" => "kursiv"
				,"en" => "italic"
				)
			,"link:noun1" => array(
				"sv" => "länk:ar"
				,"en" => "link:es"
				)
			,"list of members:noun1" => array(
				"sv" => "medlemslista:_or:n:na"
				,"en" => "list of members:s"
				)
			,"location:noun1" => array(
				"sv" => "plats:er:en:na"
				,"en" => "location:s"
				)
			,"median:noun1" => array(
				"sv" => "median:er:-"
				,"en" => "median:s"
				)
			,"member:noun1" => array(
				"sv" => "medlem:mar:men:na:-s"
				,"en" => "member:s"
				)
			,"member's:noun1" => array(
				"sv" => "medlemmens"
				,"en" => "member's"
				)
			,"member admin:noun1" => array(
				"sv" => "medlemsansvarig:a"
				,"en" => "member admin:s"
				)
			,"month:noun1" => array(
				"sv" => "månad:er:en:na"
				,"en" => "month:s"
				)
			,"municipality:noun1" => array(
				"sv" => "kommun:er:en:na"
				,"en" => "municipality:_ies"
				)
			,"outbox:noun1" => array(
				"sv" => "skickade"
				,"en" => "outbox"
				)
			,"other:noun1" => array(
				"sv" => "annan:___dra"
				,"en" => "other:s"
				)
			,"page:noun1" => array(
				"sv" => "sida:_or:n:na"
				,"en" => "page:s"
				)
			,"participant:noun1" => array(
				"sv" => "deltagare::n:_na"
				,"en" => "participant:s"
				)
			,"permission:noun1" => array(
				"sv" => "behörighet:er:en:na"
				,"en" => "permission:s"
				)
			,"phrase:noun1" => array(
				"sv" => "fras:er:en:na"
				,"en" => "phrase:s"
				)
			,"popularity:noun1" => array(
				"sv" => "populäritet"
				,"en" => "popularity"
				)
			,"priority:noun1" => array(
				"sv" => "prioritet:er:-s"
				,"en" => "priority:_ies"
				)
			,"profile:noun1" => array(
				"sv" => "profil:er:en:erna:-"
				,"en" => "profile:s"
				)
			,"proposition:noun1" => array(
				"sv" => "proposition:er:en:erna"
				,"en" => "proposition:s"
				)
			,"recipient:noun1" => array(
				"sv" => "mottagare::n:_na"
				,"en" => "recipient:s"
				)
			,"removal:noun1" => array(
				"sv" => "borttagning"
				,"en" => "removal"
				)				
			,"role:noun1" => array(
				"sv" => "roll:er:en:erna"
				,"en" => "role:s"
				)
			,"search:noun1" => array(
				"sv" => "sök:ningar:ningen:ningarna:-"
				,"en" => "search:es"
				)
			,"sender:noun1" => array(
				"sv" => "avsändare::n:_na"
				,"en" => "sender:s"
				)
			,"setting:noun1" => array(
				"sv" => "inställning:ar"
				,"en" => "setting:s"
				)
			,"start:noun1" => array(
				"sv" => "start:er:en:na"
				,"en" => "start:s"
				)
			,"street:noun1" => array(
				"sv" => "gata:or:-_u"
				,"en" => "street:s"
				)
			,"subforum:noun1" => array(
				"sv" => "underforum::et:en"
				,"en" => "subforum:s"
				)
			,"supporter:noun1" => array(
				"sv" => "stödjare::n:_na"
				,"en" => "supporter:s"
				)
			,"telephone:noun1" => array(
				"sv" => "telefon:er:en:na:-"
				,"en" => "telephone:s"
				)
			,"thread:noun1" => array(
				"sv" => "tråd:ar:en:na:-"
				,"en" => "thread:s"
				)
			,"time:noun1" => array(
				"sv" => "tidpunkt:er"
				,"en" => "time:s"
				)
			,"time of vote:noun1" => array(
				"sv" => "Röstningstidpunkt"
				,"en" => "Time of vote"
				)
			,"title:noun1" => array(
				"sv" => "titel"
				,"en" => "title"
				)
			,"type:noun1" => array(
				"sv" => "typ"
				,"en" => "type"
				)
			,"underline:noun1" => array(
				"sv" => "understruken"
				,"en" => "underline"
				)
			,"update:noun1" => array(
				"sv" => "uppdatering"
				,"en" => "update"
				)
			,"user:noun1" => array(
				"sv" => "användare::n:_na"
				,"en" => "user:s"
				)
			,"user information:noun1" => array(
				"sv" => "uppgifter"
				,"en" => "user information"
				)
			,"[your]vote:noun1" => array(
				"sv" => "röst:er:en:erna"
				,"en" => "vote:s"
				)
			,"vote:noun1" => array(
				"sv" => "omröstning:ar:en:na:-s"
				,"en" => "vote:s"
				)
			,"vote admin:noun1" => array(
				"sv" => "valadministratör:er"
				,"en" => "vote admin:s"
				)
			,"vote count:noun1" => array(
				"sv" => "ställningen i denna omröstning"
				,"en" => "vote count:s"
				)
			,"vote time:noun1" => array(
				"sv" => "omröstningstid:er:en:na"
				,"en" => "vote time:s"
				)
			,"vote type:noun1" => array(
				"sv" => "omröstningstyp:er:en:na"
				,"en" => "vote type:s"
				)
			,"vote's:noun1" => array(
				"sv" => "omröstnings:_ars:_ens"
				,"en" => "vote's:__s'"
				)
			,"voter:noun1" => array(
				"sv" => "röstande"
				,"en" => "voter"
				)
			,"week:noun1" => array(
				"sv" => "vecka:_or:n:na"
				,"en" => "week:s"
				)
			,"workgroup:noun1" => array(
				"sv" => "arbetsgrupp:er:en:na"
				,"en" => "workgroup:s"
				)

			//NOUNS, variation 2
			,"addition:noun2" => array(
				"sv" => "tillägg"
				,"en" => "addition"
				)
			,"alternative:noun2" => array(
				"sv" => "alternativ::et:en"
				,"en" => "alternative:s"
				)
			,"candidate election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "candidate election:s"
				)
			,"date:noun2" => array(
				"sv" => "datum::et:en"
				,"en" => "date:s"
				)
			,"election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "election:s"
				)
			,"error:noun2" => array(
				"sv" => "fel::et:en"
				,"en" => "error:s"
				)
			,"forum:noun2" => array(
				"sv" => "forum::et:en:-"
				,"en" => "forum:s"
				)
			,"line:noun2" => array(
				"sv" => "streck::et:en"
				,"en" => "line:s"
				)
			,"membership:noun2" => array(
				"sv" => "medlemskap"
				,"en" => "membership"
				)
			,"message:noun2" => array(
				"sv" => "meddelande:n"
				,"en" => "message:s"
				)
			,"name:noun2" => array(
				"sv" => "namn::et:en"
				,"en" => "name:s"
				)
			,"number:noun2" => array(
				"sv" => "nummer::___ret:___en"
				,"en" => "number:s"
				)
			,"password:noun2" => array(
				"sv" => "lösenord::et:en"
				,"en" => "password:s"
				)
			,"post:noun2" => array(
				"sv" => "inlägg::et:en"
				,"en" => "post:s"
				)
			,"proposal:noun2" => array(
				"sv" => "förslag::et:en"
				,"en" => "proposal:s"
				)
			,"quote:noun2" => array(
				"sv" => "citat::et:en"
				,"en" => "quote:s"
				)
			,"region:noun2" => array(
				"sv" => "län::et:en"
				,"en" => "region:s"
				)
			,"result:noun2" => array(
				"sv" => "resultat::et:en"
				,"en" => "result:s"
				)
			,"subject:noun2" => array(
				"sv" => "ämne"
				,"en" => "subject"
				)
			,"social security number:noun2" => array(
				"sv" => "personnummer::___ret"
				,"en" => "social security number"
				)
			,"support:noun2" => array(
				"sv" => "stöd"
				,"en" => "support"
				)
			,"topic:noun2" => array(
				"sv" => "ämne:n:t:a:-s"
				,"en" => "topic:s"
				)
			,"username:noun2" => array(
				"sv" => "användarnamn"
				,"en" => "username:s"
				)
			,"value:noun2" => array(
				"sv" => "värde"
				,"en" => "value"
				)
			,"wrong:noun2" => array(
				"sv" => "fel"
				,"en" => "wrong"
				)
			,"zip code:noun2" => array(
				"sv" => "postnummer"
				,"en" => "zip code"
				)
		);
	}	
} 
?>
