<?php
namespace Thesaurus; 

class nouns 
{
	public static function create_translations() {
		return array(
			//singular_indefinite:plural_indefinite:singular_definite:plural_definite
			"access:noun1" => array(
				"sv" => "tillgång"
				,"en" => "access"
				)
			,"action:noun1" => array(
				"sv" => "åtgärd:er:en:na"
				,"en" => "action:s"
				)
			,"active vote:noun1" => array(
				"sv" => "pågående omröstning:ar"
				,"en" => "active vote:s"
				)
			,"activity:noun1" => array(
				"sv" => "aktivitet:er:en:na"
				,"en" => "activity:_ies"
				)
			,"address:noun1" => array(
				"sv" => "adress:er:en:na"
				,"en" => "address:es"
				)
			,"admin:noun1" => array(
				"sv" => "admin:istratörer"
				,"en" => "admin:istrators"
				)
			,"administrator:noun1" => array(
				"sv" => "administratör:er:-s"
				,"en" => "administrator:s"
				)
			,"application:noun1" => array(
				"sv" => "ansökan:__ningar"
				,"en" => "application:s"
				)
			,"authorisation:noun1" => array(
				"sv" => "behörighet:er"
				,"en" => "authorisation:s"
				)
			,"ballot:noun1" => array(
				"sv" => "röst:er:en:na"
				,"en" => "ballot:s"
				)
			,"[]bold:noun1" => array(
				"sv" => "fet"
				,"en" => "bold"
				)
			,"bold:noun1" => array(
				"sv" => "fetstil"
				,"en" => "bold"
				)
			,"box:noun1" => array(
				"sv" => "ruta:_or:n:na"
				,"en" => "box:es"
				)
			,"budget:noun1" => array(
				"sv" => "budget:ar:-"
				,"en" => "budget:s"
				)
			,"button:noun1" => array(
				"sv" => "knapp:ar:en:na"
				,"en" => "button:s"
				)
			,"calendar:noun1" => array(
				"sv" => "kalender:__rar"
				,"en" => "calendar:s"
				)
			,"candidacy:noun1" => array(
				"sv" => "kandidatur:er:en:na:-"
				,"en" => "candidacy:_ies"
				)
			,"candidate:noun1" => array(
				"sv" => "kandidat:er:en:na:-"
				,"en" => "candidate:s"
				)
			,"caption:noun1" => array(
				"sv" => "rubrik:er:en:na"
				,"en" => "caption:s"
				)
			,"category:noun1" => array(
				"sv" => "kategori:er:n:na:-"
				,"en" => "category:_ies"
				)
			,"change:noun1[made]" => array(
				"sv" => "ändring:ar"
				,"en" => "change:s"
				)
			,"change:noun1" => array(
				"sv" => "förändring:ar"
				,"en" => "change:s"
				)
			,"city:noun1" => array(
				"sv" => "postort"
				,"en" => "city"
				)
			,"constituency:noun1" => array(
				"sv" => "valkrets:ar:en:na:-"
				,"en" => "constituency:_ies"
				)
			,"credential:noun1" => array(
				"sv" => "inloggningsuppgift:er"
				,"en" => "credential:s"
				)
			,"database:noun1" => array(
				"sv" => "databas:-"
				,"en" => "database"
				)
			,"day:noun1" => array(
				"sv" => "dag:ar:en:na"
				,"en" => "day:s"
				)
			,"debate:noun1" => array(
				"sv" => "debatt:er"
				,"en" => "debate:s"
				)
			,"delegand:noun1" => array(
				"sv" => "delegand:er:en:na"
				,"en" => "delegand:s"
				)
			,"delegate:noun1" => array(
				"sv" => "delegat:er:-"
				,"en" => "delegate:s"
				)
			,"delegate setting:noun1" => array(
				"sv" => "delegatinställning:ar"
				,"en" => "delegate setting:s"
				)
			,"delegation:noun1" => array(
				"sv" => "delegering:ar"
				,"en" => "delegation:s"
				)
			,"description:noun1" => array(
				"sv" => "beskrivning:ar:en:na"
				,"en" => "description:s"
				)
			,"email:noun1" => array(
				"sv" => "e-post:-"
				,"en" => "email"
				)
			,"exclusion:noun1" => array(
				"sv" => "uteslutning"
				,"en" => "exclusion"
				)
			,"file:noun1" => array(
				"sv" => "fil:er:en:na:-"
				,"en" => "file:s"
				)
			,"filtering:noun1" => array(
				"sv" => "filtrering"
				,"en" => "filtering"
				)
			,"forum access:noun1" => array(
				"sv" => "forumbehörighet"
				,"en" => "forum access"
				)
			,"forum admin:noun1" => array(
				"sv" => "forumadministratör:er"
				,"en" => "forum admin:s"
				)
			,"front page:noun1" => array(
				"sv" => "första-sida"
				,"en" => "front page"
				)
			,"group:noun1" => array(
				"sv" => "grupp:er:en:na:-"
				,"en" => "group:s"
				)
			,"history:noun1" => array(
				"sv" => "historik"
				,"en" => "history"
				)
			,"hit:noun1" => array(
				"sv" => "träff:ar"
				,"en" => "hit:s"
				)
			,"image:noun1" => array(
				"sv" => "bild:er:en:na"
				,"en" => "image:s"
				)
			,"inbox:noun1" => array(
				"sv" => "inkorgen"
				,"en" => "inbox"
				)
			,"individual:noun1" => array(
				"sv" => "privatperson"
				,"en" => "individual"
				)
			,"information:noun1" => array(
				"sv" => "information"
				,"en" => "information"
				)
			,"italic:noun1" => array(
				"sv" => "kursiv"
				,"en" => "italic"
				)
			,"link:noun1" => array(
				"sv" => "länk:ar"
				,"en" => "link:es"
				)
			,"list:noun1" => array(
				"sv" => "lista:_or:n:na"
				,"en" => "list:s"
				)
			,"list of members:noun1" => array(
				"sv" => "medlemslista:_or:n:na"
				,"en" => "list of members:s"
				)
			,"location:noun1" => array(
				"sv" => "plats:er:en:na"
				,"en" => "location:s"
				)
			,"median:noun1" => array(
				"sv" => "median:er:-"
				,"en" => "median:s"
				)
			,"member:noun1" => array(
				"sv" => "medlem:mar:men:na:-s"
				,"en" => "member:s"
				)
			,"member admin:noun1" => array(
				"sv" => "medlemsansvarig:a"
				,"en" => "member admin:s"
				)
			,"member-page:noun1" => array(
				"sv" => "medlems-sida:_or:n:na"
				,"en" => "member-page:s"
				)
			,"membership application:noun1" => array(
				"sv" => "medlemsansökan"
				,"en" => "membership application"
				)
			,"minute:noun1" => array(
				"sv" => "minut:er:en:na"
				,"en" => "minute:s"
				)
			,"moderator:noun1" => array(
				"sv" => "moderator:er:n:na"
				,"en" => "moderator:s"
				)
			,"month:noun1" => array(
				"sv" => "månad:er:en:na"
				,"en" => "month:s"
				)
			,"municipality:noun1" => array(
				"sv" => "kommun:er:en:na"
				,"en" => "municipality:_ies"
				)
			,"outbox:noun1" => array(
				"sv" => "skickade"
				,"en" => "outbox"
				)
			,"other:noun1" => array(
				"sv" => "annan:___dra"
				,"en" => "other:s"
				)
			,"page:noun1" => array(
				"sv" => "sida:_or:n:na"
				,"en" => "page:s"
				)
			,"participant:noun1" => array(
				"sv" => "deltagare::n:_na"
				,"en" => "participant:s"
				)
			,"permission:noun1" => array(
				"sv" => "behörighet:er:en:na"
				,"en" => "permission:s"
				)
			,"phrase:noun1" => array(
				"sv" => "fras:er:en:na"
				,"en" => "phrase:s"
				)
			,"possibility:noun1" => array(
				"sv" => "möjlighet:er:en:na"
				,"en" => "possibility:_ies"
				)
			,"popularity:noun1" => array(
				"sv" => "populäritet"
				,"en" => "popularity"
				)
			,"presentation:noun1" => array(
				"sv" => "presentation:er:en:na"
				,"en" => "presentation:s"
				)
			,"priority:noun1" => array(
				"sv" => "prioritet:er:-s"
				,"en" => "priority:_ies"
				)
			,"profile:noun1" => array(
				"sv" => "profil:er:en:erna:-"
				,"en" => "profile:s"
				)
			,"proposed vote:noun1" => array(
				"sv" => "föreslagen omröstning"
				,"en" => "proposed vote"
				)
			,"proposition:noun1" => array(
				"sv" => "proposition:er:en:erna"
				,"en" => "proposition:s"
				)
			,"question:noun1" => array(
				"sv" => "fråga:_or:n:na"
				,"en" => "question:s"
				)
			,"recipient:noun1" => array(
				"sv" => "mottagare::n:_na"
				,"en" => "recipient:s"
				)
			,"removal:noun1" => array(
				"sv" => "borttagning"
				,"en" => "removal"
				)				
			,"repetition:noun1" => array(
				"sv" => "upprepning:ar"
				,"en" => "repetition:s"
				)				
			,"report:noun1" => array(
				"sv" => "anmälan"
				,"en" => "report"
				)				
			,"role:noun1" => array(
				"sv" => "roll:er:en:na"
				,"en" => "role:s"
				)
			,"search:noun1" => array(
				"sv" => "sök:ningar:ningen:na:-"
				,"en" => "search:es"
				)
			,"sender:noun1" => array(
				"sv" => "avsändare::n:_na"
				,"en" => "sender:s"
				)
			,"session:noun1" => array(
				"sv" => "session:er:en:na"
				,"en" => "session:s"
				)
			,"setting:noun1" => array(
				"sv" => "inställning:ar"
				,"en" => "setting:s"
				)
			,"sort order:noun1" => array(
				"sv" => "sortering:ar:en:na"
				,"en" => "sort order:s"
				)
			,"start:noun1" => array(
				"sv" => "start:er:en:na"
				,"en" => "start:s"
				)
			,"street:noun1" => array(
				"sv" => "gata:or:-_u"
				,"en" => "street:s"
				)
			,"subforum:noun1" => array(
				"sv" => "underforum::et:en"
				,"en" => "subforum:s"
				)
			,"subscription:noun1" => array(
				"sv" => "anmälan"
				,"en" => "subscription"
				)
			,"support-ballot:noun1" => array(
				"sv" => "stöd-röst:er:en:na"
				,"en" => "support-ballot:s"
				)
			,"supporter:noun1" => array(
				"sv" => "stödjare::n:_na"
				,"en" => "supporter:s"
				)
			,"telephone:noun1" => array(
				"sv" => "telefon:er:en:na:-"
				,"en" => "telephone:s"
				)
			,"text:noun1" => array(
				"sv" => "text:er:en:na:-"
				,"en" => "text:s"
				)
			,"thread:noun1" => array(
				"sv" => "tråd:ar:en:na:-"
				,"en" => "thread:s"
				)
			/*
			,"thread start:noun1" => array(
				"sv" => "trådstart:er:en:na"
				,"en" => "thread start:s"
				)
			*/
			,"time:noun1" => array(
				"sv" => "tidpunkt:er:_____en:na"
				,"en" => "time:s"
				)
			,"time of vote:noun1" => array(
				"sv" => "Röstningstidpunkt"
				,"en" => "Time of vote"
				)
			,"title:noun1" => array(
				"sv" => "titel"
				,"en" => "title"
				)
			,"treasurer:noun1" => array(
				"sv" => "kassör"
				,"en" => "treasurer"
				)
			,"type:noun1" => array(
				"sv" => "typ:er:en:na"
				,"en" => "type:s"
				)
			,"underline:noun1" => array(
				"sv" => "understruken"
				,"en" => "underline"
				)
			,"update:noun1" => array(
				"sv" => "uppdatering:ar:en:na"
				,"en" => "update:s"
				)
			,"user:noun1" => array(
				"sv" => "användare::n:_na:-_"
				,"en" => "user:s"
				)
			,"user information:noun1" => array(
				"sv" => "användaruppgifter"
				,"en" => "user information"
				)
			,"[your]vote:noun1" => array(
				"sv" => "röst:er:en:na"
				,"en" => "vote:s"
				)
			,"vote:noun1" => array(
				"sv" => "omröstning:ar:en:na:-s"
				,"en" => "vote:s"
				)
			,"vote admin:noun1" => array(
				"sv" => "valadministratör:er"
				,"en" => "vote admin:s"
				)
			,"vote count:noun1" => array(
				"sv" => "ställningen i denna omröstning"
				,"en" => "vote count:s"
				)
			,"vote time:noun1" => array(
				"sv" => "omröstningstid:er:en:na"
				,"en" => "vote time:s"
				)
			,"voter:noun1" => array(
				"sv" => "röstande"
				,"en" => "voter"
				)
			,"voting:noun1" => array(
				"sv" => "röstning"
				,"en" => "voting"
				)
			,"week:noun1" => array(
				"sv" => "vecka:_or:n:na"
				,"en" => "week:s"
				)
			,"workgroup:noun1" => array(
				"sv" => "arbetsgrupp:er:en:na"
				,"en" => "workgroup:s"
				)

			//NOUNS, variation 2
			,"addition:noun2" => array(
				"sv" => "tillägg"
				,"en" => "addition"
				)
			,"alternative:noun2" => array(
				"sv" => "alternativ::et:en"
				,"en" => "alternative:s"
				)
			,"candidate election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "candidate election:s"
				)
			,"date:noun2" => array(
				"sv" => "datum::et:en"
				,"en" => "date:s"
				)
			,"election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "election:s"
				)
			,"error:noun2" => array(
				"sv" => "fel::et:en"
				,"en" => "error:s"
				)
			,"field:noun2" => array(
				"sv" => "fält::et:en"
				,"en" => "field:s"
				)
			,"forum:noun2" => array(
				"sv" => "forum::et:en:-"
				,"en" => "forum:s"
				)
			,"given name:noun2" => array(
				"sv" => "förnamn"
				,"en" => "given name"
				)
			,"last name:noun2" => array(
				"sv" => "efternamn"
				,"en" => "last name"
				)
			,"line:noun2" => array(
				"sv" => "streck::et:en"
				,"en" => "line:s"
				)
			,"membership:noun2" => array(
				"sv" => "medlemskap"
				,"en" => "membership"
				)
			,"message:noun2" => array(
				"sv" => "meddelande:n:t:na"
				,"en" => "message:s"
				)
			,"message-text:noun2" => array(
				"sv" => "meddelande-text:er:en:na"
				,"en" => "message-text:s"
				)
			,"name:noun2" => array(
				"sv" => "namn::et:en"
				,"en" => "name:s"
				)
			,"news letter:noun2" => array(
				"sv" => "nyhetsbrev::et:en"
				,"en" => "news letter:s"
				)
			,"number:noun2[of]" => array(
				"sv" => "antal::et:en"
				,"en" => "number:s of"
				)
			,"number:noun2" => array(
				"sv" => "nummer::___ret:___en"
				,"en" => "number:s"
				)
			,"one or more mandatory field:noun2" => array(
				"sv" => "ett eller fler obligatoriska fält"
				,"en" => "one or more mandatory field:s"
				)
			,"password:noun2" => array(
				"sv" => "lösenord::et:en"
				,"en" => "password:s"
				)
			,"post:noun2" => array(
				"sv" => "inlägg::et:en"
				,"en" => "post:s"
				)
			,"proposal:noun2" => array(
				"sv" => "förslag::et:en"
				,"en" => "proposal:s"
				)
			,"quote:noun2" => array(
				"sv" => "citat::et:en"
				,"en" => "quote:s"
				)
			,"region:noun2" => array(
				"sv" => "län::et:en"
				,"en" => "region:s"
				)
			,"result:noun2" => array(
				"sv" => "resultat::et:en"
				,"en" => "result:s"
				)
			,"subject:noun2" => array(
				"sv" => "ämne"
				,"en" => "subject"
				)
			,"social security number:noun2" => array(
				"sv" => "personnummer::___ret"
				,"en" => "social security number"
				)
			,"support:noun2" => array(
				"sv" => "stöd"
				,"en" => "support"
				)
			,"topic:noun2" => array(
				"sv" => "ämne:n:t:a:-s"
				,"en" => "topic:s"
				)
			,"username:noun2" => array(
				"sv" => "användarnamn::et:en"
				,"en" => "username:s"
				)
			,"value:noun2" => array(
				"sv" => "värde"
				,"en" => "value"
				)
			,"vote alternative:noun2" => array(
				"sv" => "omröstningsalternativ::et:en"
				,"en" => "vote alternative:s"
				)
			,"wrong:noun2" => array(
				"sv" => "fel"
				,"en" => "wrong"
				)
			,"year:noun2" => array(
				"sv" => "år"
				,"en" => "year"
				)
			,"zip code:noun2" => array(
				"sv" => "postnummer"
				,"en" => "zip code"
				)
		);
	}	
} 
?>
