<?php
namespace Thesaurus; 

class nouns 
{
	public static function create_translations() {
		return array(
			//singular_indefinite:plural_indefinite:singular_definite:plural_definite
			"active vote:noun1" => array(
				"sv" => "pågående omröstning:ar"
				,"en" => "active vote:s"
				)
			,"address:noun1" => array(
				"sv" => "adress"
				,"en" => "address"
				)
			,"admin:noun1" => array(
				"sv" => "admin:istratörer"
				,"en" => "admin:istrators"
				)
			,"administrator:noun1" => array(
				"sv" => "administratör:er:-s"
				,"en" => "administrator:s"
				)
			,"application:noun1" => array(
				"sv" => "ansökning:ar"
				,"en" => "application:s"
				)
			,"authorisation:noun1" => array(
				"sv" => "behörighet:er"
				,"en" => "authorisation:s"
				)
			,"ballot:noun1" => array(
				"sv" => "röst:er:en:na"
				,"en" => "ballot:s"
				)
			,"box:noun1" => array(
				"sv" => "ruta:_or:n:na"
				,"en" => "box:es"
				)
			,"budget:noun1" => array(
				"sv" => "budget:ar:-"
				,"en" => "budget:s"
				)
			,"button:noun1" => array(
				"sv" => "knapp:ar:en:na"
				,"en" => "button:s"
				)
			,"calendar:noun1" => array(
				"sv" => "kalender:__rar"
				,"en" => "calendar:s"
				)
			,"candidacy:noun1" => array(
				"sv" => "kandidatur:er:en:na:-"
				,"en" => "candidacy:_ies"
				)
			,"candidate:noun1" => array(
				"sv" => "kandidat:er:en:na:-"
				,"en" => "candidate:s"
				)
			,"caption:noun1" => array(
				"sv" => "rubrik:er:en:na"
				,"en" => "caption:s"
				)
			,"category:noun1" => array(
				"sv" => "kategori:er"
				,"en" => "category:_ies"
				)
			,"change:noun1" => array(
				"sv" => "förändring:ar"
				,"en" => "change:s"
				)
			,"city:noun1" => array(
				"sv" => "postort"
				,"en" => "city"
				)
			,"constituency:noun1" => array(
				"sv" => "valkrets:ar:en:na:-"
				,"en" => "constituency:_ies"
				)
			,"debate:noun1" => array(
				"sv" => "debatt:er"
				,"en" => "debate:s"
				)
			,"delegate:noun1" => array(
				"sv" => "delegat:er:-"
				,"en" => "delegate:s"
				)
			,"delegate setting:noun1" => array(
				"sv" => "delegatinställning:ar"
				,"en" => "delegate setting:s"
				)
			,"delegation:noun1" => array(
				"sv" => "delegering:ar"
				,"en" => "delegation:s"
				)
			,"description:noun1" => array(
				"sv" => "beskrivning:ar"
				,"en" => "description:s"
				)
			,"email:noun1" => array(
				"sv" => "e-post"
				,"en" => "email"
				)
			,"exclusion:noun1" => array(
				"sv" => "uteslutning"
				,"en" => "exclusion"
				)
			,"forum admin:noun1" => array(
				"sv" => "forumadministratör:er"
				,"en" => "forum admin:s"
				)
			,"front page:noun1" => array(
				"sv" => "första-sida"
				,"en" => "front page"
				)
			,"group:noun1" => array(
				"sv" => "grupp:er:-"
				,"en" => "group:s"
				)
			,"inbox:noun1" => array(
				"sv" => "inkorgen"
				,"en" => "inbox"
				)
			,"individual:noun1" => array(
				"sv" => "privatperson"
				,"en" => "individual"
				)
			,"link:noun1" => array(
				"sv" => "länk:ar"
				,"en" => "link:es"
				)
			,"list of members:noun1" => array(
				"sv" => "medlemslista:_or:n:na"
				,"en" => "list of members:s"
				)
			,"median:noun1" => array(
				"sv" => "median:er:-"
				,"en" => "median:s"
				)
			,"member:noun1" => array(
				"sv" => "medlem:mar:men:na:-s"
				,"en" => "member:s"
				)
			,"member admin:noun1" => array(
				"sv" => "medlemsansvarig:a"
				,"en" => "member admin:s"
				)
			,"municipality:noun1" => array(
				"sv" => "kommun"
				,"en" => "municipality"
				)
			,"phrase:noun1" => array(
				"sv" => "fras:er:en:na"
				,"en" => "phrase:s"
				)
			,"profile:noun1" => array(
				"sv" => "profil:er"
				,"en" => "profile:s"
				)
			,"outbox:noun1" => array(
				"sv" => "skickade"
				,"en" => "outbox"
				)
			,"other:noun1" => array(
				"sv" => "annan:___dra"
				,"en" => "other:s"
				)
			,"page:noun1" => array(
				"sv" => "sida:_or:n:na"
				,"en" => "page:s"
				)
			,"popularity:noun1" => array(
				"sv" => "populäritet"
				,"en" => "popularity"
				)
			,"priority:noun1" => array(
				"sv" => "prioritet:er:-s"
				,"en" => "priority:_ies"
				)
			,"proposition:noun1" => array(
				"sv" => "proposition:er:en:erna"
				,"en" => "proposition:s"
				)
			,"recipient:noun1" => array(
				"sv" => "mottagare::n:_na"
				,"en" => "recipient:s"
				)
			,"removal:noun1" => array(
				"sv" => "borttagning"
				,"en" => "removal"
				)				
			,"role:noun1" => array(
				"sv" => "roll:er:en:erna"
				,"en" => "role:s"
				)
			,"sender:noun1" => array(
				"sv" => "avsändare::n:_na"
				,"en" => "sender:s"
				)
			,"setting:noun1" => array(
				"sv" => "inställning:ar"
				,"en" => "setting:s"
				)
			,"social security number:noun1" => array(
				"sv" => "personnummer"
				,"en" => "social security number"
				)
			,"street:noun1" => array(
				"sv" => "gata:or:-_u"
				,"en" => "street:s"
				)
			,"supporter:noun1" => array(
				"sv" => "stödjare::n:_na"
				,"en" => "supporter:s"
				)
			,"telephone:noun1" => array(
				"sv" => "telefon"
				,"en" => "telephone"
				)
			,"time:noun1" => array(
				"sv" => "tidpunkt:er"
				,"en" => "time:s"
				)
			,"time of vote:noun1" => array(
				"sv" => "Röstningstidpunkt"
				,"en" => "Time of vote"
				)
			,"title:noun1" => array(
				"sv" => "titel"
				,"en" => "title"
				)
			,"type:noun1" => array(
				"sv" => "typ"
				,"en" => "type"
				)
			,"user:noun1" => array(
				"sv" => "användare"
				,"en" => "user:s"
				)
			,"[your]vote:noun1" => array(
				"sv" => "röst:er:en:erna"
				,"en" => "vote:s"
				)
			,"vote:noun1" => array(
				"sv" => "omröstning:ar:en:arna:-s"
				,"en" => "vote:s"
				)
			,"vote time:noun1" => array(
				"sv" => "omröstningstid:er:en:erna"
				,"en" => "vote time:s"
				)
			,"vote admin:noun1" => array(
				"sv" => "valadministratör:er"
				,"en" => "vote admin:s"
				)
			,"vote's:noun1" => array(
				"sv" => "omröstnings"
				,"en" => "vote's"
				)
			,"voter:noun1" => array(
				"sv" => "röstande"
				,"en" => "voter"
				)
			,"workgroup:noun1" => array(
				"sv" => "arbetsgrupp:er:en:na"
				,"en" => "workgroup:s"
				)

			//NOUNS, variation 2
			,"alternative:noun2" => array(
				"sv" => "alternativ::et:en"
				,"en" => "alternative:s"
				)
			,"candidate election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "candidate election:s"
				)
			,"date:noun2" => array(
				"sv" => "datum::et:en"
				,"en" => "date:s"
				)
			,"election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "election:s"
				)
			,"forum:noun2" => array(
				"sv" => "forum::-"
				,"en" => "forum:s"
				)
			,"membership:noun2" => array(
				"sv" => "medlemskap"
				,"en" => "membership"
				)
			,"message:noun2" => array(
				"sv" => "meddelande:n"
				,"en" => "message:s"
				)
			,"name:noun2" => array(
				"sv" => "namn::et:en"
				,"en" => "name:s"
				)
			,"password:noun2" => array(
				"sv" => "lösenord::et:en"
				,"en" => "password:s"
				)
			,"post:noun2" => array(
				"sv" => "inlägg::et:en"
				,"en" => "post:s"
				)
			,"proposal:noun2" => array(
				"sv" => "förslag::et:en"
				,"en" => "proposal:s"
				)
			,"subject:noun2" => array(
				"sv" => "ämne"
				,"en" => "subject"
				)
			,"support:noun2" => array(
				"sv" => "stöd"
				,"en" => "support"
				)
			,"username:noun2" => array(
				"sv" => "användarnamn"
				,"en" => "username:s"
				)
			,"value:noun2" => array(
				"sv" => "värde"
				,"en" => "value"
				)
			,"zip code:noun2" => array(
				"sv" => "postnummer"
				,"en" => "zip code"
				)
		);
	}	
} 
?>
