<?php
namespace Thesaurus; 

class phrases 
{
	public static function create_translations() {
		return array(
			"a continuous vote will also be created" => array(
				"sv" => "kommer det också att skapas en kontinuerlig omröstning"
				,"en" => "a continuous vote will also be created"
				)
			,"it also means" => array(
				"sv" => "det innebär också"
				,"en" => "it also means"
				)
			,"as follows" => array(
				"sv" => "följande"
				,"en" => "as follows"
				)
			,"be seen" => array(
				"sv" => "ses"
				,"en" => "be seen"
				)
			,"by filling" => array(
				"sv" => "genom att fylla i"
				,"en" => "by filling"
				)
			,"[]candidate in" => array(
				"sv" => "kandidat in"
				,"en" => "candidate in"
				)
			,"currently members" => array(
				"sv" => "medlemmar för närvarande"
				,"en" => "currently members"
				)
			,"delete selected" => array(
				"sv" => "radera valda"
				,"en" => "delete selected"
				)
			,"did never read it" => array(
				"sv" => "hann aldrig läsa det"
				,"en" => "did never read it"
				)
			,"didn't match" => array(
				"sv" => "matchade inte"
				,"en" => "didn't match"
				)
			,"do you really want to" => array(
				"sv" => "vill du verkligen"
				,"en" => "do you really want to"
				)
			,"doesn't support" => array(
				"sv" => "stöder ej"
				,"en" => "doesn't support"
				)
			,"don't support" => array(
				"sv" => "stödjer inte"
				,"en" => "don't support"
				)
			,"for the particular issue" => array(
				"sv" => "i den frågan"
				,"en" => "från the particular issue"
				)
			,"for which you have registerered your delegacy" => array(
				"sv" => "som du angivit för din delegat"
				,"en" => "for which you have registerered your delegacy"
				)
			,"forum topic-id" => array(
				"sv" => "forumtråds-ID"
				,"en" => "forum topic-ID"
				)
			,"here you create" => array(
				"sv" => "här skapar man"
				,"en" => "here you create"
				)
			,"in a row" => array(
				"sv" => "i rad"
				,"en" => "in a row"
				)
			,"in association with" => array(
				"sv" => "i samband med"
				,"en" => "in association with"
				)
			,"in the same way" => array(
				"sv" => "på samma sätt"
				,"en" => "in the same way"
				)
			,"is not free" => array(
				"sv" => "inte är öppet"
				,"en" => "is not free"
				)
			,"it cannot be removed" => array(
				"sv" => "kan det inte tas bort"
				,"en" => "it cannot be removed"
				)
			,"it is not possible" => array(
				"sv" => "det går inte"
				,"en" => "it is not possible"
				)
			,"it is possible" => array(
				"sv" => "finns möjligheten"
				,"en" => "it is possible"
				)
			,"it will be transformed" => array(
				"sv" => "kommer den att omvandlas"
				,"en" => "will be transformed"
				)
			,"last login" => array(
				"sv" => "senast inloggad"
				,"en" => "last login"
				)
			,"one of the mandatory fields" => array(
				"sv" => "något av de obligatoriska fälten"
				,"en" => "one of the mandatory fields"
				)
			,"reply to" => array(
				"sv" => "svar till"
				,"en" => "reply to"
				)
			,"signed up for" => array(
				"sv" => "anmäld till"
				,"en" => "signed up for"
				)
			,"the activation of this workgroup" => array(
				"sv" => "denna arbetsgrupps aktivering"
				,"en" => "the activation of this workgroup"
				)
			,"the creation of this workgroup" => array(
				"sv" => "att arbetsgruppen skapas"
				,"en" => "the creation of this workgroup"
				)
			,"their vote" => array(
				"sv" => "sin röst"
				,"en" => "their vote"
				)
			,"there are" => array(
				"sv" => "det finns"
				,"en" => "there are"
				)
			,"this is not appropriate" => array(
				"sv" => "detta inte är lämpligt"
				,"en" => "this is not appropriate"
				)
			,"this means" => array(
				"sv" => "det innebär"
				,"en" => "this means"
				)
			,"to the calendar" => array(
				"sv" => "i kalendern"
				,"en" => "to the calendar"
				)
			,"vote (yes/no)" => array(
				"sv" => "votering (ja/nej)"
				,"en" => "vote (yes/no)"
				)
			,"vote status" => array(
				"sv" => "omröstningens status"
				,"en" => "vote status"
				)
			,"whereof" => array(
				"sv" => "varav"
				,"en" => "whereof"
				)
			,"workgroup election" => array(
				"sv" => "personval för arbetsgrupp"
				,"en" => "workgroup election"
				)
			,"you don't have to" => array(
				"sv" => "behöver du inte"
				,"en" => "you don't have to"
				)
			,"you press" => array(
				"sv" => "trycker du på"
				,"en" => "you press"
				)
		);
	}	
}
