<?php
namespace Thesaurus; 

class phrases 
{
	public static function create_translations() {
		return array(
			// UNCLASSIFIED
			"a continous vote will also be created" => array(
				"sv" => "kommer det också att skapas en kontinuerlig omröstning"
				,"en" => "a continous vote will also be created"
				)
			,"after" => array(
				"sv" => "efter att"
				,"en" => "after"
				)
			,"after the vote has been created" => array(
				"sv" => "efter att omröstningen har skapats"
				,"en" => "after the vote has been created"
				)
			,"all" => array(
				"sv" => "alla"
				,"en" => "all"
				)
			,"all those" => array(
				"sv" => "alla"
				,"en" => "all those"
				)
			,"alphabetic" => array(
				"sv" => "alfabetisk"
				,"en" => "alphabetic"
				)
			,"also" => array(
				"sv" => "också"
				,"en" => "also"
				)
			,"also means" => array(
				"sv" => "innebär också"
				,"en" => "also means"
				)
			,"are" => array(
				"sv" => "är"
				,"en" => "are"
				)
			,"are appointed" => array(
				"sv" => "utses"
				,"en" => "are appointed"
				)
			,"as" => array(
				"sv" => "som"
				,"en" => "as"
				)
			,"automatically" => array(
				"sv" => "automatiskt"
				,"en" => "automatically"
				)
			,"back" => array(
				"sv" => "tillbaka"
				,"en" => "back"
				)
			,"be given" => array(
				"sv" => "ges"
				,"en" => "be given"
				)
			,"be seen" => array(
				"sv" => "ses"
				,"en" => "be seen"
				)
			,"become a" => array(
				"sv" => "bli"
				,"en" => "become a"
				)
			,"been removed" => array(
				"sv" => "tagits bort"
				,"en" => "been removed"
				)
			,"by filling the form" => array(
				"sv" => "genom att fylla i formuläret"
				,"en" => "by filling the form"
				)
			,"can be created" => array(
				"sv" => "kan skapas"
				,"en" => "can be created"
				)
			,"can be found" => array(
				"sv" => "finns"
				,"en" => "can be found"
				)
			,"candidate in" => array(
				"sv" => "kandidat in"
				,"en" => "candidate in"
				)
			,"cannot be undone" => array(
				"sv" => "kan inte ångras"
				,"en" => "cannot be undone"
				)
			,"currently the number of members is %d" => array(
				"sv" => "just nu är antalet medlemmar %d st"
				,"en" => "currently the number of members is"
				)
			,"delegate voting closes" => array(
				"sv" => "delegatröstning avslutas"
				,"en" => "delegate voting closes"
				)
			,"directly" => array(
				"sv" => "direkt"
				,"en" => "directly"
				)
			,"do you really want to" => array(
				"sv" => "vill du verkligen"
				,"en" => "do you really want to"
				)
			,"do you still want to continue" => array(
				"sv" => "vill du fortsätta ändå"
				,"en" => "do you still want to continue"
				)
			,"doesn't support" => array(
				"sv" => "stöder ej"
				,"en" => "doesn't support"
				)
			,"even" => array(
				"sv" => "även"
				,"en" => "even"
				)
			,"for the particular issue" => array(
				"sv" => "i den frågan"
				,"en" => "från the particular issue"
				)
			,"for which you have registerered your delegacy" => array(
				"sv" => "som du angivit för din delegat"
				,"en" => "for which you have registerered your delegacy"
				)
			,"forum topic-id" => array(
				"sv" => "forumtråds-ID"
				,"en" => "forum topic-ID"
				)
			,"found" => array(
				"sv" => "funna"
				,"en" => "found"
				)
			,"given name" => array(
				"sv" => "förnamn"
				,"en" => "given name"
				)
			,"half" => array(
				"sv" => "halva"
				,"en" => "half"
				)
			,"has been cast" => array(
				"sv" => "är lagd"
				,"en" => "has been cast"
				)
			,"has voted" => array(
				"sv" => "röstat"
				,"en" => "has voted"
				)
			,"has voted for you" => array(
				"sv" => "har röstat åt dig"
				,"en" => "has voted for you"
				)
			,"have" => array(
				"sv" => "har"
				,"en" => "have"
				)
			,"have cast your own ballot" => array(
				"sv" => "har lagt din egen röst"
				,"en" => "have cast your own ballot"
				)
			,"have let your delegate vote" => array(
				"sv" => "har låtit din delegat rösta"
				,"en" => "have let your delegate vote"
				)
			,"hello" => array(
				"sv" => "hej"
				,"en" => "hello"
				)
			,"here" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"here you create" => array(
				"sv" => "här skapar man"
				,"en" => "here you create"
				)
			,"if" => array(
				"sv" => "om"
				,"en" => "if"
				)
			,"if you want to" => array(
				"sv" => "vill du"
				,"en" => "if you want to"
				)
			,"in a row" => array(
				"sv" => "i rad"
				,"en" => "in a row"
				)
			,"in association with" => array(
				"sv" => "i samband med"
				,"en" => "in association with"
				)
			,"in case" => array(
				"sv" => "ifall"
				,"en" => "in case"
				)
			,"in the same way" => array(
				"sv" => "på samma sätt"
				,"en" => "in the same way"
				)
			,"in which" => array(
				"sv" => "inom vilka"
				,"en" => "in which"
				)
			,"instead of" => array(
				"sv" => "istället för"
				,"en" => "instead of"
				)
			,"is activated" => array(
				"sv" => "aktiveras"
				,"en" => "is activated"
				)
			,"is not free" => array(
				"sv" => "inte är öppet"
				,"en" => "is not free"
				)
			,"is not possible" => array(
				"sv" => "går inte"
				,"en" => "is not possible"
				)
			,"it cannot be removed" => array(
				"sv" => "kan det inte tas bort"
				,"en" => "it cannot be removed"
				)
			,"it continues until it is ended through a new yes/no vote" => array(
				"sv" => "den fortsätter tills en votering bestämmer att den ska avslutas"
				,"en" => "it continues until it is ended through a new yes/no vote"
				)
			,"it finished" => array(
				"sv" => "den avslutades"
				,"en" => "it finished"
				)
			,"it is possible" => array(
				"sv" => "finns möjligheten"
				,"en" => "it is possible"
				)
			,"it needs at least three members to be activated" => array(
				"sv" => "för att bli aktiv måste den ha minst tre medlemmar"
				,"en" => "it needs at least three members to be activated"
				)
			,"it to be subject for vote is" => array(
				"sv" => "att den ska godkännas och gå vidare till omröstning är"
				,"en" => "it to be subject for vote is"
				)
			,"it will be transformed" => array(
				"sv" => "kommer den att omvandlas"
				,"en" => "it will be transformed"
				)
			,"its content has not yet been decided" => array(
				"sv" => "beslut om dess innehåll är ännu inte fattat"
				,"en" => "its content has not yet been decided"
				)
			,"just" => array(
				"sv" => "bara"
				,"en" => "just"
				)
			,"last login" => array(
				"sv" => "senast inloggad"
				,"en" => "last login"
				)
			,"last name" => array(
				"sv" => "efternamn"
				,"en" => "last name"
				)
			,"me" => array(
				"sv" => "mig"
				,"en" => "me"
				)
			,"message not found" => array(
				"sv" => "kan inte hitta meddelandet"
				,"en" => "message not found"
				)
			,"name of" => array(
				"sv" => "namn på"
				,"en" => "name of"
				)
			,"necessary" => array(
				"sv" => "nödvändigt"
				,"en" => "necessary"
				)
			,"no[]" => array(
				"sv" => "nej"
				,"en" => "no"
				)
			,"not yet" => array(
				"sv" => "ännu inte"
				,"en" => "not yet"
				)
			,"number of" => array(
				"sv" => "antal"
				,"en" => "number of"
				)
			,"on proposition" => array(
				"sv" => "på propositionen"
				,"en" => "on proposition"
				)
			,"only" => array(
				"sv" => "bara"
				,"en" => "only"
				)
			,"out" => array(
				"sv" => "ut"
				,"en" => "out"
				)
			,"other than" => array(
				"sv" => "annat än"
				,"en" => "other than"
				)
			,"process application" => array(
				"sv" => "hantera ansökan"
				,"en" => "process application"
				)
			,"personally" => array(
				"sv" => "personligt"
				,"en" => "personally"
				)
			,"proposition created" => array(
				"sv" => "propositionen skapad"
				,"en" => "proposition created"
				)
			,"proposition's" => array(
				"sv" => "propositions"
				,"en" => "proposition's"
				)
			,"re" => array(
				"sv" => "sv"
				,"en" => "re"
				)
			,"register as candidate for" => array(
				"sv" => "anmäl dig som kandidat i"
				,"en" => "register as candidate for"
				)
			,"registered as a delegate" => array(
				"sv" => "registrerad som delegat"
				,"en" => "registered as a delegate"
				)
			,"reject application" => array(
				"sv" => "avslå ansökan"
				,"en" => "reject application"
				)
			,"revoke ballot" => array(
				"sv" => "ångra röst"
				,"en" => "revoke ballot"
				)
			,"so" => array(
				"sv" => "så"
				,"en" => "so"
				)
			,"stop supporting" => array(
				"sv" => "sluta stödja"
				,"en" => "stop supporting"
				)
			,"subscribe for" => array(
				"sv" => "anmäl dig till"
				,"en" => "subscribe for"
				)
			,"superadmin" => array(
				"sv" => "superadmin"
				,"en" => "superadmin"
				)
			,"supporting" => array(
				"sv" => "stöder"
				,"en" => "supporting"
				)
			,"that" => array(
				"sv" => "att"
				,"en" => "that"
				)
			,"the admittance of this candidate" => array(
				"sv" => "att denna kandidat upptas"
				,"en" => "the admittance of this candidate"
				)
			,"the creation of this workgroup" => array(
				"sv" => "att arbetsgruppen skapas"
				,"en" => "the creation of this workgroup"
				)
			,"the possibility to vote closed" => array(
				"sv" => "stängdes möjligheten att rösta"
				,"en" => "the possibility to vote closed"
				)
			,"the possibility to vote closes" => array(
				"sv" => "stänger möjligheten att rösta"
				,"en" => "the possibility to vote closes"
				)
			,"their vote" => array(
				"sv" => "sin röst"
				,"en" => "their vote"
				)
			,"this" => array(
				"sv" => "denna"
				,"en" => "this"
				)
			,"this is" => array(
				"sv" => "det här är"
				,"en" => "this is"
				)
			,"this is not appropriate" => array(
				"sv" => "detta inte är lämpligt"
				,"en" => "this is not appropriate"
				)
			,"this means" => array(
				"sv" => "det innebär"
				,"en" => "this means"
				)
			,"those" => array(
				"sv" => "de"
				,"en" => "those"
				)
			,"through" => array(
				"sv" => "via"
				,"en" => "through"
				)
			,"to be subject for" => array(
				"sv" => "för att gå vidare och bli"
				,"en" => "to be subject for"
				)
			,"to stop supporting" => array(
				"sv" => "för att sluta stödja"
				,"en" => "to stop supporting"
				)
			,"together" => array(
				"sv" => "tillsammans"
				,"en" => "together"
				)
			,"treasurer" => array(
				"sv" => "kassör"
				,"en" => "treasurer"
				)
			,"unsubscribe for" => array(
				"sv" => "avanmäl dig till"
				,"en" => "unsubscribe for"
				)
			,"upcoming" => array(
				"sv" => "kommande"
				,"en" => "upcoming"
				)
			,"visible to" => array(
				"sv" => "synlig för"
				,"en" => "visible to"
				)
			,"vote (yes/no)" => array(
				"sv" => "votering (ja/nej)"
				,"en" => "vote (yes/no)"
				)
			,"vote as delegate" => array(
				"sv" => "rösta som delegat"
				,"en" => "vote as delegate"
				)
			,"vote closes" => array(
				"sv" => "omröstningen avslutas"
				,"en" => "vote closes"
				)
			,"vote started" => array(
				"sv" => "Omröstningen startad"
				,"en" => "vote started"
				)
			,"vote status" => array(
				"sv" => "Omröstningens status"
				,"en" => "vote status"
				)
			,"want the activity to be repeated" => array(
				"sv" => "vill att aktiviteten ska upprepas"
				,"en" => "want the activity to be repeated"
				)
			,"was found" => array(
				"sv" => "hittades"
				,"en" => "was found"
				)
			,"was terminated" => array(
				"sv" => "avslutades"
				,"en" => "was terminated"
				)
			,"welcome" => array(
				"sv" => "välkommen"
				,"en" => "welcome"
				)
			,"will be activated" => array(
				"sv" => "kommer aktiveras"
				,"en" => "will be activated"
				)
			,"will be completely deleted" => array(
				"sv" => "kommer att raderas fullständigt"
				,"en" => "will be completely deleted"
				)
			,"with a restricted number of members" => array(
				"sv" => "vars medlemsantal är begränsat"
				,"en" => "with a restricted number of members"
				)
			,"when" => array(
				"sv" => "när"
				,"en" => "when"
				)
			,"where" => array(
				"sv" => "där"
				,"en" => "where"
				)
			,"whereof" => array(
				"sv" => "varav"
				,"en" => "whereof"
				)
			,"who" => array(
				"sv" => "som"
				,"en" => "who"
				)
			,"yes" => array(
				"sv" => "ja"
				,"en" => "yes"
				)
			,"you create" => array(
				"sv" => "skapar du"
				,"en" => "you create"
				)
			,"you don't have to vote as delegate" => array(
				"sv" => "behöver du inte rösta som delegat"
				,"en" => "you don't have to vote as delegate"
				)
			,"you have cast" => array(
				"sv" => "du har själv lagt"
				,"en" => "you have cast"
				)
			,"you press" => array(
				"sv" => "trycker du på"
				,"en" => "you press"
				)
			,"[]you vote" => array(
				"sv" => "du röstar"
				,"en" => "you vote"
				)
			,"you vote" => array(
				"sv" => "röstar du"
				,"en" => "you vote"
				)
			,"you vote for" => array(
				"sv" => "du röstar för"
				,"en" => "you vote for"
				)
			,"you vote and support propositions" => array(
				"sv" => "röstar du och stödjer propositioner"
				,"en" => "you vote and support propositions"
				)
		);
	}	
} 
?>
