<?php
namespace Thesaurus; 
class phrases 
{
	public static function create_translations() {
		return array(
			// UNCLASSIFIED
			"a continous vote will also be created" => array(
				"sv" => "kommer det också att skapas en kontinuerlig omröstning"
				,"en" => "a continous vote will also be created"
				)
			,"a member of" => array(
				"sv" => "medlem i"
				,"en" => "a member of"
				)
			,"after" => array(
				"sv" => "efter att"
				,"en" => "after"
				)
			,"after half" => array(
				"sv" => "efter halva"
				,"en" => "after half"
				)
			,"after the vote has been created" => array(
				"sv" => "efter att omröstningen har skapats"
				,"en" => "after the vote has been created"
				)
			,"again" => array(
				"sv" => "igen"
				,"en" => "again"
				)
			,"all those" => array(
				"sv" => "alla"
				,"en" => "all those"
				)
			,"alphabetic" => array(
				"sv" => "alfabetisk"
				,"en" => "alphabetic"
				)
			,"already" => array(
				"sv" => "redan"
				,"en" => "already"
				)
			,"also" => array(
				"sv" => "också"
				,"en" => "also"
				)
			,"also means" => array(
				"sv" => "innebär också"
				,"en" => "also means"
				)
			,"another" => array(
				"sv" => "ett annat"
				,"en" => "another"
				)
			,"are appointed" => array(
				"sv" => "utses"
				,"en" => "are appointed"
				)
			,"are elected" => array(
				"sv" => "är valda"
				,"en" => "are elected"
				)
			,"as delegate" => array(
				"sv" => "som delegat"
				,"en" => "as delegate"
				)
			,"as follows" => array(
				"sv" => "följande"
				,"en" => "as follows"
				)
			,"automatically" => array(
				"sv" => "automatiskt"
				,"en" => "automatically"
				)
			,"back" => array(
				"sv" => "tillbaka"
				,"en" => "back"
				)
			,"be created" => array(
				"sv" => "skapas"
				,"en" => "be created"
				)
			,"be deleted" => array(
				"sv" => "raderas"
				,"en" => "be deleted"
				)
			,"be edited" => array(
				"sv" => "redigeras"
				,"en" => "be edited"
				)
			,"be given" => array(
				"sv" => "ges"
				,"en" => "be given"
				)
			,"be seen" => array(
				"sv" => "ses"
				,"en" => "be seen"
				)
			,"become a" => array(
				"sv" => "bli"
				,"en" => "become a"
				)
			,"been appended" => array(
				"sv" => "försätts med tillägg"
				,"en" => "been appended"
				)
			,"been removed" => array(
				"sv" => "tagits bort"
				,"en" => "been removed"
				)
			,"both" => array(
				"sv" => "både"
				,"en" => "both"
				)
			,"by filling the form" => array(
				"sv" => "genom att fylla i formuläret"
				,"en" => "by filling the form"
				)
			,"by email" => array(
				"sv" => "via e-post"
				,"en" => "by email"
				)
			,"can be created" => array(
				"sv" => "kan skapas"
				,"en" => "can be created"
				)
			,"can be found" => array(
				"sv" => "finns"
				,"en" => "can be found"
				)
			,"[]candidate in" => array(
				"sv" => "kandidat in"
				,"en" => "candidate in"
				)
			,"candidate in" => array(
				"sv" => "kandidat i"
				,"en" => "candidate in"
				)
			,"cannot be undone" => array(
				"sv" => "kan inte ångras"
				,"en" => "cannot be undone"
				)
			,"could not" => array(
				"sv" => "kunde inte"
				,"en" => "could not"
				)
			,"currently members" => array(
				"sv" => "medlemmar för närvarande"
				,"en" => "currently members"
				)
			,"currently the number of members is %d" => array(
				"sv" => "just nu är antalet medlemmar %d st"
				,"en" => "currently the number of members is %d"
				)
			,"delegate voting closes" => array(
				"sv" => "delegatröstning avslutas"
				,"en" => "delegate voting closes"
				)
			,"delete selected[]" => array(
				"sv" => "radera valda"
				,"en" => "delete selected"
				)
			,"didn't match" => array(
				"sv" => "matchade inte"
				,"en" => "didn't match"
				)
			,"did never read it" => array(
				"sv" => "hann aldrig läsa det"
				,"en" => "did never read it"
				)
			,"directly" => array(
				"sv" => "direkt"
				,"en" => "directly"
				)
			,"don't have" => array(
				"sv" => "har inte"
				,"en" => "don't have"
				)
			,"does not have" => array(
				"sv" => "har inte"
				,"en" => "does not have"
				)
			,"don't support" => array(
				"sv" => "stödjer inte"
				,"en" => "don't support"
				)
			,"do you really want to" => array(
				"sv" => "vill du verkligen"
				,"en" => "do you really want to"
				)
			,"do you still want to continue" => array(
				"sv" => "vill du fortsätta ändå"
				,"en" => "do you still want to continue"
				)
			,"doesn't exist" => array(
				"sv" => "finns inte"
				,"en" => "doesn't exist"
				)
			,"doesn't match" => array(
				"sv" => "matchar inte"
				,"en" => "doesn't match"
				)
			,"doesn't support" => array(
				"sv" => "stöder ej"
				,"en" => "doesn't support"
				)
			,"even" => array(
				"sv" => "även"
				,"en" => "even"
				)
			,"every" => array(
				"sv" => "varje"
				,"en" => "every"
				)
			,"for the particular issue" => array(
				"sv" => "i den frågan"
				,"en" => "från the particular issue"
				)
			,"for which you have registerered your delegacy" => array(
				"sv" => "som du angivit för din delegat"
				,"en" => "for which you have registerered your delegacy"
				)
			,"forum topic-id" => array(
				"sv" => "forumtråds-ID"
				,"en" => "forum topic-ID"
				)
			,"found" => array(
				"sv" => "funna"
				,"en" => "found"
				)
			,"half" => array(
				"sv" => "halva"
				,"en" => "half"
				)
			,"given name" => array(
				"sv" => "förnamn"
				,"en" => "given name"
				)
			,"got" => array(
				"sv" => "fått"
				,"en" => "got"
				)
			,"half" => array(
				"sv" => "halva"
				,"en" => "half"
				)
			,"has been cast" => array(
				"sv" => "är lagd"
				,"en" => "has been cast"
				)
			,"has been created" => array(
				"sv" => "har skapats"
				,"en" => "has been created"
				)
			,"has been deleted" => array(
				"sv" => "har raderats"
				,"en" => "has been deleted"
				)
			,"has been edited" => array(
				"sv" => "har redigerats"
				,"en" => "has been edited"
				)
			,"has been moved" => array(
				"sv" => "har flyttats"
				,"en" => "has been moved"
				)
			,"has been revoked" => array(
				"sv" => "har ångrats"
				,"en" => "has been revoked"
				)
			,"has been registered" => array(
				"sv" => "har registrerats"
				,"en" => "has been registered"
				)
			,"has been sent" => array(
				"sv" => "har skickats"
				,"en" => "has been sent"
				)
			,"has been restored" => array(
				"sv" => "har återställts"
				,"en" => "has been restored"
				)
			,"has been updated" => array(
				"sv" => "har uppdaterats"
				,"en" => "has been updated"
				)
			,"has been withdrawn" => array(
				"sv" => "har dragits tillbaka"
				,"en" => "has been withdrawn"
				)
			,"has voted" => array(
				"sv" => "röstat"
				,"en" => "has voted"
				)
			,"has voted for you" => array(
				"sv" => "har röstat åt dig"
				,"en" => "has voted for you"
				)
			,"have" => array(
				"sv" => "har"
				,"en" => "have"
				)
			,"have been accepted" => array(
				"sv" => "har blivit antagen"
				,"en" => "have been accepted"
				)
			,"have been sent" => array(
				"sv" => "har skickats"
				,"en" => "have been sent"
				)
			,"have cast your own ballot" => array(
				"sv" => "har lagt din egen röst"
				,"en" => "have cast your own ballot"
				)
			,"have let your delegate vote" => array(
				"sv" => "har låtit din delegat rösta"
				,"en" => "have let your delegate vote"
				)
			,"hello" => array(
				"sv" => "hej"
				,"en" => "hello"
				)
			,"here" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"here you create" => array(
				"sv" => "här skapar man"
				,"en" => "here you create"
				)
			,"if" => array(
				"sv" => "om"
				,"en" => "if"
				)
			,"if you want to" => array(
				"sv" => "vill du"
				,"en" => "if you want to"
				)
			,"if you want to support" => array(
				"sv" => "om du vill stödja"
				,"en" => "if you want to support"
				)
			,"included as member" => array(
				"sv" => "upptagen som medlem"
				,"en" => "included as member"
				)
			,"in a row" => array(
				"sv" => "i rad"
				,"en" => "in a row"
				)
			,"in association with" => array(
				"sv" => "i samband med"
				,"en" => "in association with"
				)
			,"in case" => array(
				"sv" => "ifall"
				,"en" => "in case"
				)
			,"in the same way" => array(
				"sv" => "på samma sätt"
				,"en" => "in the same way"
				)
			,"in which" => array(
				"sv" => "inom vilka"
				,"en" => "in which"
				)
			,"instead of" => array(
				"sv" => "istället för"
				,"en" => "instead of"
				)
			,"is activated" => array(
				"sv" => "aktiveras"
				,"en" => "is activated"
				)
			,"is not free" => array(
				"sv" => "inte är öppet"
				,"en" => "is not free"
				)
			,"is not possible" => array(
				"sv" => "går inte"
				,"en" => "is not possible"
				)
			,"it cannot be removed" => array(
				"sv" => "kan det inte tas bort"
				,"en" => "it cannot be removed"
				)
			,"it continues until it is ended through a new yes/no vote" => array(
				"sv" => "den fortsätter tills en votering bestämmer att den ska avslutas"
				,"en" => "it continues until it is ended through a new yes/no vote"
				)
			,"it finished" => array(
				"sv" => "den avslutades"
				,"en" => "it finished"
				)
			,"it is possible" => array(
				"sv" => "finns möjligheten"
				,"en" => "it is possible"
				)
			,"it needs at least three members to be activated" => array(
				"sv" => "för att bli aktiv måste den ha minst tre medlemmar"
				,"en" => "it needs at least three members to be activated"
				)
			,"it to be subject for vote is" => array(
				"sv" => "att den ska godkännas och gå vidare till omröstning är"
				,"en" => "it to be subject for vote is"
				)
			,"it will be transformed" => array(
				"sv" => "kommer den att omvandlas"
				,"en" => "it will be transformed"
				)
			,"its content has not yet been decided" => array(
				"sv" => "beslut om dess innehåll är ännu inte fattat"
				,"en" => "its content has not yet been decided"
				)
			,"just" => array(
				"sv" => "bara"
				,"en" => "just"
				)
			,"last changed" => array(
				"sv" => "ändrades senast"
				,"en" => "last changed"
				)
			,"last login" => array(
				"sv" => "senast inloggad"
				,"en" => "last login"
				)
			,"last name" => array(
				"sv" => "efternamn"
				,"en" => "last name"
				)
			,"me" => array(
				"sv" => "mig"
				,"en" => "me"
				)
			,"message not found" => array(
				"sv" => "meddelandet kunde inte hittas"
				,"en" => "message not found"
				)
			,"recipient not found" => array(
				"sv" => "mottagaren kunde inte hittas"
				,"en" => "recipient not found"
				)
			,"must have" => array(
				"sv" => "måste ha"
				,"en" => "must have"
				)
			,"name of" => array(
				"sv" => "namn på"
				,"en" => "name of"
				)
			,"necessary" => array(
				"sv" => "nödvändigt"
				,"en" => "necessary"
				)
			,"no[]" => array(
				"sv" => "nej"
				,"en" => "no"
				)
			,"no change made" => array(
				"sv" => "ingen ändring gjord"
				,"en" => "no change made"
				)
			,"no changes made" => array(
				"sv" => "inga ändringar gjorda"
				,"en" => "no changes made"
				)
			,"no longer" => array(
				"sv" => "inte längre"
				,"en" => "no longer"
				)
			,"not" => array(
				"sv" => "inte"
				,"en" => "not"
				)
			,"not yet" => array(
				"sv" => "ännu inte"
				,"en" => "not yet"
				)
			,"now" => array(
				"sv" => "nu"
				,"en" => "now"
				)
			,"now excluded" => array(
				"sv" => "numera utesluten"
				,"en" => "now excluded"
				)
			,"number of" => array(
				"sv" => "antal"
				,"en" => "number of"
				)
			,"on proposition" => array(
				"sv" => "på propositionen"
				,"en" => "on proposition"
				)
			,"only" => array(
				"sv" => "bara"
				,"en" => "only"
				)
			,"one of the mandatory fields" => array(
				"sv" => "något av de obligatoriska fälten"
				,"en" => "one of the mandatory fields"
				)
			,"out" => array(
				"sv" => "ut"
				,"en" => "out"
				)
			,"other than" => array(
				"sv" => "annat än"
				,"en" => "other than"
				)
			,"process application" => array(
				"sv" => "hantera ansökan"
				,"en" => "process application"
				)
			,"personally" => array(
				"sv" => "personligt"
				,"en" => "personally"
				)
			,"proposition created" => array(
				"sv" => "propositionen skapad"
				,"en" => "proposition created"
				)
			,"proposition's" => array(
				"sv" => "propositions"
				,"en" => "proposition's"
				)
			,"re" => array(
				"sv" => "sv"
				,"en" => "re"
				)
			,"register as candidate for" => array(
				"sv" => "anmäl dig som kandidat i"
				,"en" => "register as candidate for"
				)
			,"registered as a delegate" => array(
				"sv" => "registrerad som delegat"
				,"en" => "registered as a delegate"
				)
			,"reject application" => array(
				"sv" => "avslå ansökan"
				,"en" => "reject application"
				)
			,"reply to" => array(
				"sv" => "svar till"
				,"en" => "reply to"
				)
			,"revoke ballot" => array(
				"sv" => "ångra röst"
				,"en" => "revoke ballot"
				)
			,"should be reported" => array(
				"sv" => "ska anmälas"
				,"en" => "should be reported"
				)
			,"signed up for:adj" => array(
				"sv" => "anmäld till"
				,"en" => "signed up for"
				)
			,"so" => array(
				"sv" => "så"
				,"en" => "so"
				)
			,"still" => array(
				"sv" => "fortfarande"
				,"en" => "still"
				)
			,"still needs more support" => array(
				"sv" => "behöver fortfarande mer stöd"
				,"en" => "still needs more support"
				)
			,"stop supporting" => array(
				"sv" => "sluta stödja"
				,"en" => "stop supporting"
				)
			,"subscribe for" => array(
				"sv" => "anmäl dig till"
				,"en" => "subscribe for"
				)
			,"subscribe to" => array(
				"sv" => "prenumerera på"
				,"en" => "subscribe to"
				)
			,"superadmin" => array(
				"sv" => "superadmin"
				,"en" => "superadmin"
				)
			,"supporting" => array(
				"sv" => "stöder"
				,"en" => "supporting"
				)
			,"thank you" => array(
				"sv" => "tack"
				,"en" => "thank you"
				)
			,"that" => array(
				"sv" => "att"
				,"en" => "that"
				)
			,"the activation of this workgroup" => array(
				"sv" => "denna arbetsgrupps aktivering"
				,"en" => "the activation of this workgroup"
				)
			,"the admittance of this candidate" => array(
				"sv" => "att denna kandidat upptas"
				,"en" => "the admittance of this candidate"
				)
			,"the creation of this workgroup" => array(
				"sv" => "att arbetsgruppen skapas"
				,"en" => "the creation of this workgroup"
				)
			,"the possibility to vote closed" => array(
				"sv" => "stängdes möjligheten att rösta"
				,"en" => "the possibility to vote closed"
				)
			,"the possibility to vote closes" => array(
				"sv" => "stänger möjligheten att rösta"
				,"en" => "the possibility to vote closes"
				)
			,"their vote" => array(
				"sv" => "sin röst"
				,"en" => "their vote"
				)
			,"there already exists" => array(
				"sv" => "det finns redan"
				,"en" => "there already exists"
				)
			,"there are" => array(
				"sv" => "det finns"
				,"en" => "there are"
				)
			,"they have been posted" => array(
				"sv" => "de postats"
				,"en" => "they have been posted"
				)
			,"this is" => array(
				"sv" => "det här är"
				,"en" => "this is"
				)
			,"this is not appropriate" => array(
				"sv" => "detta inte är lämpligt"
				,"en" => "this is not appropriate"
				)
			,"this means" => array(
				"sv" => "det innebär"
				,"en" => "this means"
				)
			,"those" => array(
				"sv" => "de"
				,"en" => "those"
				)
			,"through" => array(
				"sv" => "via"
				,"en" => "through"
				)
			,"to stop supporting" => array(
				"sv" => "för att sluta stödja"
				,"en" => "to stop supporting"
				)
			,"to the calendar" => array(
				"sv" => "i kalendern"
				,"en" => "to the calendar"
				)
			,"together" => array(
				"sv" => "tillsammans"
				,"en" => "together"
				)
			,"too" => array(
				"sv" => "för"
				,"en" => "too"
				)
			,"treasurer" => array(
				"sv" => "kassör"
				,"en" => "treasurer"
				)
			,"unsubscribe for" => array(
				"sv" => "avanmäl dig till"
				,"en" => "unsubscribe for"
				)
			,"upcoming" => array(
				"sv" => "kommande"
				,"en" => "upcoming"
				)
			,"visible to" => array(
				"sv" => "synlig för"
				,"en" => "visible to"
				)
			,"vote (yes/no)" => array(
				"sv" => "votering (ja/nej)"
				,"en" => "vote (yes/no)"
				)
			,"vote[as]" => array(
				"sv" => "rösta"
				,"en" => "vote"
				)
			,"vote closes" => array(
				"sv" => "omröstningen avslutas"
				,"en" => "vote closes"
				)
			,"vote started" => array(
				"sv" => "Omröstningen startad"
				,"en" => "vote started"
				)
			,"vote status" => array(
				"sv" => "Omröstningens status"
				,"en" => "vote status"
				)
			,"want the activity to be repeated" => array(
				"sv" => "vill att aktiviteten ska upprepas"
				,"en" => "want the activity to be repeated"
				)
			,"was found" => array(
				"sv" => "hittades"
				,"en" => "was found"
				)
			,"were found" => array(
				"sv" => "hittades"
				,"en" => "were found"
				)
			,"was not registered" => array(
				"sv" => "registrerades inte"
				,"en" => "was not registered"
				)
			,"was terminated" => array(
				"sv" => "avslutades"
				,"en" => "was terminated"
				)
			,"welcome" => array(
				"sv" => "välkommen"
				,"en" => "welcome"
				)
			,"will be activated" => array(
				"sv" => "kommer aktiveras"
				,"en" => "will be activated"
				)
			,"will be completely deleted" => array(
				"sv" => "kommer att raderas fullständigt"
				,"en" => "will be completely deleted"
				)
			,"with a restricted number of members" => array(
				"sv" => "vars medlemsantal är begränsat"
				,"en" => "with a restricted number of members"
				)
			,"when" => array(
				"sv" => "när"
				,"en" => "when"
				)
			,"where" => array(
				"sv" => "där"
				,"en" => "where"
				)
			,"whereof" => array(
				"sv" => "varav"
				,"en" => "whereof"
				)
			,"who" => array(
				"sv" => "som"
				,"en" => "who"
				)
			,"why" => array(
				"sv" => "varför"
				,"en" => "why"
				)
			,"yes" => array(
				"sv" => "ja"
				,"en" => "yes"
				)
			,"you create" => array(
				"sv" => "skapar du"
				,"en" => "you create"
				)
			,"you don't have to" => array(
				"sv" => "behöver du inte"
				,"en" => "you don't have to"
				)
			,"have personally cast" => array(
				"sv" => "har själv lagt"
				,"en" => "have personally cast"
				)
			,"you no longer support" => array(
				"sv" => "du stödjer inte längre"
				,"en" => "you no longer support"
				)
			,"you now vote" => array(
				"sv" => "nu röstar du"
				,"en" => "you now vote"
				)
			,"you act" => array(
				"sv" => "agerar du"
				,"en" => "you act"
				)
			,"you press" => array(
				"sv" => "trycker du på"
				,"en" => "you press"
				)
			,"[]you vote" => array(
				"sv" => "du röstar"
				,"en" => "you vote"
				)
			,"you vote" => array(
				"sv" => "röstar du"
				,"en" => "you vote"
				)
			,"you vote for" => array(
				"sv" => "du röstar för"
				,"en" => "you vote for"
				)
			,"you vote and support propositions" => array(
				"sv" => "röstar du och stödjer propositioner"
				,"en" => "you vote and support propositions"
				)
		);
	}	
} 
?>