<?php
namespace Thesaurus; 

class prepositions 
{
	public static function create_translations() {
		return array(
			"above:prep" => array(
				"sv" => "ovan"
				,"en" => "above"
				)
			,"above:prep[definite]" => array(
				"sv" => "ovanför"
				,"en" => "above"
				)
			,"as:prep" => array(
				"sv" => "som"
				,"en" => "as"
				)
			,"below:prep" => array(
				"sv" => "nedan"
				,"en" => "below"
				)
			,"by:prep" => array(
				"sv" => "av"
				,"en" => "by"
				)
			,"[apply]for:prep" => array(
				"sv" => "om"
				,"en" => "for"
				)
			,"[candidate]for:prep" => array(
				"sv" => "till"
				,"en" => "for"
				)
			,"[proposal]for:prep" => array(
				"sv" => "till"
				,"en" => "for"
				)
			,"for:prep[quant]" => array(
				"sv" => "under"
				,"en" => "for"
				)
			,"for:prep" => array(
				"sv" => "för"
				,"en" => "for"
				)
			,"from:prep" => array(
				"sv" => "från"
				,"en" => "from"
				)
			,"in:prep" => array(
				"sv" => "i"
				,"en" => "in"
				)
			,"[member]of:prep" => array(
				"sv" => "i"
				,"en" => "of"
				)
			,"[name]of:prep" => array(
				"sv" => "på"
				,"en" => "of"
				)
			,"[number]of:prep" => array(
				"sv" => ""
				,"en" => "of"
				)
			,"of:prep" => array(
				"sv" => "av"
				,"en" => "of"
				)
			,"on:prep" => array(
				"sv" => "på"
				,"en" => "on"
				)
			,"out:prep" => array(
				"sv" => "ut"
				,"en" => "out"
				)
			,"outside:prep" => array(
				"sv" => "utanför"
				,"en" => "outside"
				)
			,"to:prep" => array(
				"sv" => "till"
				,"en" => "to"
				)
			,"under:prep" => array(
				"sv" => "under"
				,"en" => "under"
				)
			,"with:prep" => array(
				"sv" => "med"
				,"en" => "with"
				)
			,"within:prep" => array(
				"sv" => "i"
				,"en" => "within"
				)
		);
	}	
} 
?>
