<?php
namespace Thesaurus; 

class time_and_date 
{
	public static function create_translations() {
		return array(
			//DAYS SHORT
			"mon" => array(
				"sv" => "mån"
				,"en" => "mon"
				)
			,"tue" => array(
				"sv" => "tis"
				,"en" => "tue"
				)
			,"wed" => array(
				"sv" => "ons"
				,"en" => "wed"
				)
			,"thu" => array(
				"sv" => "tor"
				,"en" => "thu"
				)
			,"fri" => array(
				"sv" => "fre"
				,"en" => "fri"
				)
			,"sat" => array(
				"sv" => "lör"
				,"en" => "sat"
				)
			,"sun" => array(
				"sv" => "sön"
				,"en" => "sun"
				)

			//DAYS
			,"monday" => array(
				"sv" => "måndag"
				,"en" => "monday"
				)
			,"tuesday" => array(
				"sv" => "tisdag"
				,"en" => "tuesday"
				)
			,"wednesday" => array(
				"sv" => "onsdag"
				,"en" => "wednesday"
				)
			,"thursday" => array(
				"sv" => "torsdag"
				,"en" => "thursday"
				)
			,"friday" => array(
				"sv" => "fredag"
				,"en" => "friday"
				)
			,"saturday" => array(
				"sv" => "lördag"
				,"en" => "saturday"
				)
			,"sunday" => array(
				"sv" => "söndag"
				,"en" => "sunday"
				)

			//Month
			,"january" => array(
				"sv" => "januari"
				,"en" => "january"
				)
			,"february" => array(
				"sv" => "februari"
				,"en" => "february"
				)
			,"march" => array(
				"sv" => "mars"
				,"en" => "march"
				)
			,"april" => array(
				"sv" => "aprill"
				,"en" => "april"
				)
			,"may" => array(
				"sv" => "maj"
				,"en" => "may"
				)
			,"june" => array(
				"sv" => "juni"
				,"en" => "june"
				)
			,"july" => array(
				"sv" => "juli"
				,"en" => "july"
				)
			,"august" => array(
				"sv" => "augusti"
				,"en" => "august"
				)
			,"september" => array(
				"sv" => "september"
				,"en" => "september"
				)
			,"october" => array(
				"sv" => "oktober"
				,"en" => "october"
				)
			,"november" => array(
				"sv" => "november"
				,"en" => "november"
				)
			,"december" => array(
				"sv" => "december"
				,"en" => "december"
				)

			//WORDS
			,"today" => array(
				"sv" => "idag"
				,"en" => "today"
				)
			,"yesterday" => array(
				"sv" => "igår"
				,"en" => "yesterday"
				)
			,"tomorrow" => array(
				"sv" => "imorgon"
				,"en" => "tomorrow"
				)

		);
	}	
} 
?>
