<?php
namespace Thesaurus; 

class verbs
{
	public static function create_translations() {
		return array(
			//VERBS
			//imperative:infinitive:present:perfect:perfect particip
			"abort:verb" => array(
				"sv" => "avbryt"
				,"en" => "abort"
				)
			,"abstain:verb" => array(
				"sv" => "avstår"
				,"en" => "abstain"
				)
			,"add:verb" => array(
				"sv" => "lägg till"
				,"en" => "add"
				)
			,"administrate:verb" => array(
				"sv" => "administrera::r:t:(d|_t:e)"
				,"en" => "administrate::|s:d:(d)"
				)
			,"apply:verb" => array(
				"sv" => "ansök:a:er:t"
				,"en" => "apply::|_ies:_ied"
				)
			,"be:verb" => array(
				"sv" => "var:a:___är:it:(ande)"
				,"en" => "be::__are|___is:en:(ing)"
				)
			,"become:verb" => array(
				"sv" => "bli::r:vit"
				,"en" => "become::|s:___ame"
				)
			,"cancel:verb" => array(
				"sv" => "avbryt"
				,"en" => "cancel"
				)
			,"candidate:verb" => array(
				"sv" => "kandidera"
				,"en" => "candidate"
				)
			,"cast:verb" => array(
				"sv" => "lägg::er:___agt:(___agd|_t:a)"
				,"en" => "cast::|s"
				)
			,"change:verb" => array(
				"sv" => "ändra"
				,"en" => "change"
				)
			,"check:verb" => array(
				"sv" => "markera::r:t:(d|_t:e)"
				,"en" => "check::|s:ed:(ed)"
				)
			,"choose:verb" => array(
				"sv" => "välj:a:er:___alt:(___ald|_t:a)"
				,"en" => "choose::|s:d:(n)"
				)
			,"click:verb" => array(
				"sv" => "klicka::r:t"
				,"en" => "click::|s:ed"
				)
			,"close:verb" => array(
				"sv" => "stäng:a:er:t:(d|_t:a)"
				,"en" => "close::|s:d:(d)"
				)
			,"create:verb" => array(
				"sv" => "skapa::r:t:(d|_t:e)"
				,"en" => "create::|s:d:(d)"
				)
			,"deactivate:verb" => array(
				"sv" => "avaktivera::r:t:(d|_t:e)"
				,"en" => "deactivate::|s:d:(d)"
				)
			,"delegate:verb" => array(
				"sv" => "delegera::r:t:(d|_t:e)"
				,"en" => "delegate::|s:d:(d)"
				)
			,"delete:verb" => array(
				"sv" => "radera::r:t:(d|_t:e)"
				,"en" => "delete::|s:d:(d)"
				)
			,"demote:verb" => array(
				"sv" => "mota::r:t:(d|_t:e)"
				,"en" => "demote::|s:d:(d)"
				)				
			,"discontinue:verb" => array(
				"sv" => "avsluta"
				,"en" => "discontinue"
				)
			,"edit:verb" => array(
				"sv" => "redigera::r:t:(d|_t:e)"
				,"en" => "edit::|s:ed:(ed)"
				)
			,"exclude:verb" => array(
				"sv" => "uteslut:a:er:it:(en|_t:__na)"
				,"en" => "exclude::|s:d:(d)"
				)
			,"finish:verb" => array(
				"sv" => "avsluta"
				,"en" => "finish"
				)
			,"finishes:verb" => array(
				"sv" => "slutar"
				,"en" => "finishes"
				)
			,"handle:verb" => array(
				"sv" => "hantera"
				,"en" => "handle"
				)
			,"have:verb" => array(
				"sv" => "ha::r:ft"
				,"en" => "have::|__s:__d"
				)
			,"leave:verb" => array(
				"sv" => "lämna"
				,"en" => "leave"
				)
			,"list:verb" => array(
				"sv" => "lista"
				,"en" => "list"
				)
			,"login:verb" => array(
				"sv" => "logga in"
				,"en" => "login"
				)
			,"logout:verb" => array(
				"sv" => "logga ut"
				,"en" => "logout"
				)
			,"note:verb" => array(
				"sv" => "notera"
				,"en" => "note"
				)
			,"order:verb" => array(
				"sv" => "rangordna"
				,"en" => "order"
				)
			,"press:verb" => array(
				"sv" => "tryck på"
				,"en" => "press"
				)
			,"promote:verb" => array(
				"sv" => "främja::r:t:(d|_t:e)"
				,"en" => "promote::|s:d:(d)"
				)				
			,"propose:verb" => array(
				"sv" => "föreslå::r:_agit:(_agen|_t:__na)"
				,"en" => "propose::|s:d:(d)"
				)				
			,"read:verb" => array(
				"sv" => "läs:a:er:t:(t:a)"
				,"en" => "read::|s:::()"
				)				
			,"reach:verb" => array(
				"sv" => "uppnå::r:tt"
				,"en" => "reach::|es:ed"
				)				
			,"register:verb" => array(
				"sv" => "registrera::r:t:(d|_t:e)"
				,"en" => "register::|s:ed:(ed)"
				)				
			,"remember:verb" => array(
				"sv" => "kom ihåg"
				,"en" => "remember"
				)				
			,"remove:verb" => array(
				"sv" => "ta::r:git bort"
				,"en" => "remove::|s:d"
				)				
			,"reply:verb" => array(
				"sv" => "svara::r:t"
				,"en" => "reply::|_ies:_ied"
				)				
			,"resume:verb" => array(
				"sv" => "återuppta"
				,"en" => "resume"
				)				
			,"revoke:verb" => array(
				"sv" => "återta"
				,"en" => "revoke"
				)				
			,"search:verb" => array(
				"sv" => "sök"
				,"en" => "search"
				)
			,"see:verb" => array(
				"sv" => "se"
				,"en" => "see"
				)
			,"send:verb" => array(
				"sv" => "skicka::r:t:(d|_t:e)"
				,"en" => "send::|s|ing:_t:(_t)"
				)
			,"show:verb" => array(
				"sv" => "visa::r:t:(d|_t:e)"
				,"en" => "show::|s|ing:n:(n)"
				)
			,"support:verb" => array(
				"sv" => "stöd:ja:jer"
				,"en" => "support::|s"
				)
			,"transform:verb" => array(
				"sv" => "gör om"
				,"en" => "transform"
				)
			,"undo:verb" => array(
				"sv" => "ångra"
				,"en" => "undo"
				)
			,"update:verb" => array(
				"sv" => "uppdatera"
				,"en" => "update"
				)
			,"view:verb" => array(
				"sv" => "visa"
				,"en" => "view"
				)
			,"vote:verb" => array(
				"sv" => "rösta"
				,"en" => "vote"
				)
			,"[]vote for:verb" => array(
				"sv" => "rösta för"
				,"en" => "vote for"
				)
			,"voted:verb" => array(
				"sv" => "röstat"
				,"en" => "voted"
				)
			,"will:verb" => array(
				"sv" => "kommer"
				,"en" => "will"
				)
			,"withdraw:verb" => array(
				"sv" => "dra::r:git tillbaka"
				,"en" => "withdraw::|s:n"
				)
			,"write:verb" => array(
				"sv" => "skriv"
				,"en" => "write"
				)

			//AUXILIARY VERBS
			//imperative:infinitive:present:perfect
			,"be able to:verb-aux" => array(
				"sv" => "kunna"
				,"en" => "be able to"
				)
			,"can:verb-aux" => array(
				"sv" => "kan"
				,"en" => "can"
				)
			,"let:verb-aux" => array(
				"sv" => "låta"
				,"en" => "let"
				)
			,"may:verb-aux" => array(
				"sv" => "kan"
				,"en" => "may"
				)
			,"want to:verb-aux" => array(
				"sv" => "vill"
				,"en" => "want::|s to"
				)
			,"shall:verb-aux" => array(
				"sv" => "ska"
				,"en" => "shall"
				)
			,"[]you can:verb-aux" => array(
				"sv" => "du kan"
				,"en" => "you can"
				)
			,"you can:verb-aux" => array(
				"sv" => "kan du"
				,"en" => "you can"
				)
		);
	}	
} 
?>
