<?php
namespace Thesaurus; 

class verbs
{
	public static function create_translations() {
		return array(
			//VERBS
			//imperative:infinitive:present|singular|particip:preteritum|singular:perfect
			//:(perfect particip=adjective):passive
			"abort:verb" => array(
				"sv" => "avbryt"
				,"en" => "abort"
				)
			,"abstain:verb" => array(
				"sv" => "avstår"
				,"en" => "abstain"
				)
			,"act:verb" => array(
				"sv" => "agera::r:de:t"
				,"en" => "act::|s:ed"
				)
			,"activate:verb" => array(
				"sv" => "aktivera::r:de:t:(d|_t:e):s"
				,"en" => "activate::|s:d"
				)
			,"add:verb" => array(
				"sv" => "lägg till"
				,"en" => "add"
				)
			,"administrate:verb" => array(
				"sv" => "administrera::r:de:t:(d|_t:e):s"
				,"en" => "administrate::|s:d"
				)
			,"append:verb" => array(
				"sv" => "försett:a:er:___atte:___ett:(__dd|__tt:a):s med tillägg"
				,"en" => "append::|s:ed"
				)
			,"apply:verb" => array(
				"sv" => "ansök:a:er:te:t"
				,"en" => "apply::|_ies:_ied"
				)
			,"appoint:verb" => array(
				"sv" => "utse::r:_åg:tt"
				,"en" => "appoint::|s:ed"
				)
			,"be:verb" => array(
				"sv" => "var:a:___är::it"
				,"en" => "be::__are|___is:__were|___as:en"
				)
			/*
			,"be created:verb" => array(
				"sv" => "skapas"
				,"en" => "be created"
				)
			*/
			,"become:verb" => array(
				"sv" => "bli::r:_ev:vit"
				,"en" => "become::|s:___ame:"
				)
			,"cancel:verb" => array(
				"sv" => "avbryt"
				,"en" => "cancel"
				)
			,"candidate:verb" => array(
				"sv" => "kandidera"
				,"en" => "candidate"
				)
			,"cast:verb" => array(
				"sv" => "lägg::er:___ade:___agt:(___agd|_t:a):s"
				,"en" => "cast::|s:"
				)
			,"change:verb" => array(
				"sv" => "ändra::r:de:t:(d|_t:e):s"
				,"en" => "change::|s:d"
				)
			,"check:verb" => array(
				"sv" => "markera::r:de:t:(d|_t:e):s"
				,"en" => "check::|s:ed"
				)
			,"choose:verb" => array(
				"sv" => "välj:a:er:___alde:___alt:(___ald|_t:a):s"
				,"en" => "choose::|s:___se:n"
				)
			,"click:verb" => array(
				"sv" => "klicka::r:de:t"
				,"en" => "click::|s:ed"
				)
			,"close:verb" => array(
				"sv" => "stäng:a:er:de:t:(d|_t:a):s"
				,"en" => "close::|s:d"
				)
			,"create:verb" => array(
				"sv" => "skapa::r:de:t:(d|_t:e):s"
				,"en" => "create::|s:d"
				)
			,"deactivate:verb" => array(
				"sv" => "avaktivera::r:de:t:(d|_t:e):s"
				,"en" => "deactivate::|s:d"
				)
			,"delegate:verb" => array(
				"sv" => "delegera::r:de:t:(d|_t:e):s"
				,"en" => "delegate::|s:d"
				)
			,"delete:verb" => array(
				"sv" => "radera::r:de:t:(d|_t:e):s"
				,"en" => "delete::|s:d"
				)
			,"demote:verb" => array(
				"sv" => "mota::r:de:t:(d|_t:e):s"
				,"en" => "demote::|s:d"
				)				
			,"discontinue:verb" => array(
				"sv" => "avsluta"
				,"en" => "discontinue"
				)
			,"don't have:verb" => array(
				"sv" => "har inte"
				,"en" => "don't have"
				)
			,"edit:verb" => array(
				"sv" => "redigera::r:de:t:(d|_t:e):s"
				,"en" => "edit::|s:ed"
				)
			,"elect:verb" => array(
				"sv" => "välj:a:er:___alde:___alt:(___ald|_t:a):s"
				,"en" => "elect::|s:ed"
				)
			,"exclude:verb" => array(
				"sv" => "uteslut:a:er:__öt:it:(en|_t:__na):s"
				,"en" => "exclude::|s:d"
				)
			,"exist:verb" => array(
				"sv" => "finns:_as::____anns:____unnits"
				,"en" => "exist::|s:ed"
				)
			,"find:verb" => array(
				"sv" => "hitta::r:de:t:(_____funnen|_t:__a):s"
				,"en" => "find::|s:___ound"
				)
			,"finish:verb" => array(
				"sv" => "avsluta"
				,"en" => "finish"
				)
			,"finished:verb" => array(
				"sv" => "avslutades"
				,"en" => "finished"
				)
			,"finishes:verb" => array(
				"sv" => "slutar"
				,"en" => "finishes"
				)
			,"generate:verb" => array(
				"sv" => "skapa::r:de:t:(d|t:e):s"
				,"en" => "generate::|s:d"
				)
			,"give:verb" => array(
				"sv" => "ge::r:_av:_ivit"
				,"en" => "give::|s:___ave:n"
				)
			,"handle:verb" => array(
				"sv" => "hantera"
				,"en" => "handle"
				)
			,"have:verb" => array(
				"sv" => "ha::r:de:ft"
				,"en" => "have::|__s:__d"
				)
			,"get:verb" => array(
				"sv" => "få::r:_ick:tt"
				,"en" => "get::|s:__ot"
				)
			,"leave:verb" => array(
				"sv" => "lämna"
				,"en" => "leave"
				)
			,"list:verb" => array(
				"sv" => "lista"
				,"en" => "list"
				)
			,"login:verb" => array(
				"sv" => "logga in"
				,"en" => "login"
				)
			,"logout:verb" => array(
				"sv" => "logga ut"
				,"en" => "logout"
				)
			,"make:verb" => array(
				"sv" => "gör:a::__jorde:__jort:(__jord|_t:a):s"
				,"en" => "make::|s:__de"
				)
			,"miss:verb" => array(
				"sv" => "sakna::r:de:t:(d|t:de):s"
				,"en" => "miss::|es|ing:ed"
				)
			,"moderate:verb" => array(
				"sv" => "moderera"
				,"en" => "moderate"
				)
			,"move:verb" => array(
				"sv" => "flytta::r:de:t:(d|_t:e):s"
				,"en" => "move::|s|ing:d"
				)
			,"motivate:verb" => array(
				"sv" => "motivera"
				,"en" => "motivate"
				)
			,"note:verb" => array(
				"sv" => "notera"
				,"en" => "note"
				)
			,"order:verb" => array(
				"sv" => "rangordna"
				,"en" => "order"
				)
			,"pass:verb" => array(
				"sv" => "passera::r:de:t"
				,"en" => "pass::|es:ed"
				)
			,"press:verb" => array(
				"sv" => "tryck på"
				,"en" => "press"
				)
			,"process:verb" => array(
				"sv" => "hantera::r:de:t:(d|_t:e):s"
				,"en" => "process::|es:ed"
				)				
			,"promote:verb" => array(
				"sv" => "främja::r:de:t:(d|_t:e):s"
				,"en" => "promote::|s:d"
				)				
			,"propose:verb" => array(
				"sv" => "föreslå::r:_og:_agit:(_agen|_t:__na):s"
				,"en" => "propose::|s:d"
				)				
			,"quote:verb" => array(
				"sv" => "citera::r:de:t:(d|_t:e):s"
				,"en" => "quote::|s:d"
				)				
			,"receive:verb" => array(
				"sv" => "motta::r:_og:git:(gen|_t:__na):s"
				,"en" => "receive::|s:d"
				)				
			,"read:verb" => array(
				"sv" => "läs:a:er:te:t:(t:a):s"
				,"en" => "read::|s:"
				)				
			,"reach:verb" => array(
				"sv" => "uppnå::r:dde:tt"
				,"en" => "reach::|es:ed"
				)				
			,"register:verb" => array(
				"sv" => "registrera::r:de:t:(d|_t:e):s"
				,"en" => "register::|s:ed"
				)				
			,"reject:verb" => array(
				"sv" => "avslå"
				,"en" => "reject"
				)
			,"report:verb" => array(
				"sv" => "anmäl:a:er:de:t:(d|t:e):s"
				,"en" => "report::|s:ed"
				)				
			,"remember:verb" => array(
				"sv" => "kom ihåg"
				,"en" => "remember"
				)				
			,"remove:verb" => array(
				"sv" => "ta::r:_og:git bort"
				,"en" => "remove::|s:d"
				)				
			,"repeat:verb" => array(
				"sv" => "upprepa::r:de:t:de:(d|_t:e):s"
				,"en" => "repeat::|s:ed"
				)				
			,"replace:verb" => array(
				"sv" => "ersätta::_er:____atte:____att"
				,"en" => "replace::|s:d"
				)				
			,"reply:verb" => array(
				"sv" => "svara::r:de:t"
				,"en" => "reply::|_ies:_ied"
				)				
			,"restore:verb" => array(
				"sv" => "återställ"
				,"en" => "restore"
				)				
			,"resume:verb" => array(
				"sv" => "återuppta"
				,"en" => "resume"
				)				
			,"revoke:verb" => array(
				"sv" => "återta"
				,"en" => "revoke"
				)				
			,"search:verb" => array(
				"sv" => "sök"
				,"en" => "search"
				)
			,"see:verb" => array(
				"sv" => "se"
				,"en" => "see"
				)
			,"select:verb" => array(
				"sv" => "välj::er:___alde:___alt:(___ald|_t:a):s"
				,"en" => "select::|s|ing:ed"
				)
			,"send:verb" => array(
				"sv" => "skicka::r:de:t:(d|_t:e):s"
				,"en" => "send::|s|ing:_t"
				)
			,"set:verb" => array(
				"sv" => "ställ in"
				,"en" => "set"
				)
			,"show:verb" => array(
				"sv" => "visa::r:de:t:(d|_t:e):s"
				,"en" => "show::|s|ing:ed:ed:(n)"
				)
			,"start:verb" => array(
				"sv" => "starta::r:de:t:(d|t:e):s"
				,"en" => "start::|s:ed"
				)
			,"stop:verb" => array(
				"sv" => "sluta::r:de:t"
				,"en" => "stop::|s:ed"
				)
			,"submit:verb" => array(
				"sv" => "skicka::r:de:t in"
				,"en" => "submit::|s:ted"
				)
			,"subscribe:verb" => array(
				"sv" => "anmäl:a:er:de:t:(d|_t:a):s"
				,"en" => "subscribe::|s:d"
				)
			,"[]subscribe to:verb" => array(
				"sv" => "anmäl dig till"
				,"en" => "subscribe to"
				)
			,"subscribe to:verb" => array(
				"sv" => "prenumerera på"
				,"en" => "subscribe to"
				)
			,"support:verb" => array(
				"sv" => "stöd:ja:jer:de:_tt"
				,"en" => "support::|s|ing:ed"
				)
			,"terminate:verb" => array(
				"sv" => "avsluta::r:de:t:(d|_t:e):s"
				,"en" => "terminate::|s:d"
				)
			/*
			,"to be subject for:verb" => array(
				"sv" => "för att gå vidare och bli"
				,"en" => "to be subject for"
				)
			*/
			,"transform:verb" => array(
				"sv" => "gör om"
				,"en" => "transform"
				)
			,"undo:verb" => array(
				"sv" => "ångra::r:de:t:(d|t:e):s"
				,"en" => "undo::|es:_id:ne"
				)
			,"unsubscribe from:verb" => array(
				"sv" => "avanmäl dig från"
				,"en" => "unsubscribe from"
				)
			,"update:verb" => array(
				"sv" => "uppdatera::r:de:t:(d|_t:e):s"
				,"en" => "update::|s:d"
				)
			,"view:verb" => array(
				"sv" => "visa"
				,"en" => "view"
				)
			,"vote:verb" => array(
				"sv" => "rösta::r:de:t"
				,"en" => "vote::|s:d"
				)
			/*
			,"[]vote for:verb" => array(
				"sv" => "rösta för"
				,"en" => "vote for"
				)
			*/
/*
			,"voted:verb" => array(
				"sv" => "röstat"
				,"en" => "voted"
				)
				*/
			,"go:verb" => array(
				"sv" => "gå::r:_ick"
				,"en" => "go::|es:__went"
				)
			/*
			,"was:verb" => array(
				"sv" => "var"
				,"en" => "was"
				)
			,"were:verb" => array(
				"sv" => "var"
				,"en" => "were"
				)
			*/
/*
			,"will:verb" => array(
				"sv" => "kommer"
				,"en" => "will"
				)
				*/
			,"withdraw:verb" => array(
				"sv" => "dra::r:_og:git:():s tillbaka"
				,"en" => "withdraw::|s:__ew:n"
				)
			,"write:verb" => array(
				"sv" => "skriv"
				,"en" => "write"
				)
/*
			//PASSIVE FORMS
			,"missing:verb-pass" => array(
				"sv" => "saknas"
				,"en" => "missing"
				)
*/
			//AUXILIARY VERBS
			//imperative:infinitive:present:perfect
			,"be:verb-aux" => array(
				"sv" => "::::"
				,"en" => "be::__are|___is:__were|___as:en"
				)
			,"be able to:verb-aux" => array(
				"sv" => "kunna"
				,"en" => "be able to"
				)
			,"can:verb-aux" => array(
				"sv" => "kan:__unna::__unde"
				,"en" => "can:::__ould"
				)
			,"cannot:verb-aux" => array(
				"sv" => "kan inte"
				,"en" => "cannot"
				)
/*			,"has been:verb-aux" => array(
				"sv" => "har"
				,"en" => "has been"
				)
				*/
			,"have:verb-aux" => array(
				"sv" => "ha::r:de:ft"
				,"en" => "have::|__s:__d"
				)
			/*
			,"have been:verb-aux" => array(
				"sv" => "har"
				,"en" => "have been"
				)
			*/
			,"let:verb-aux" => array(
				"sv" => "låta"
				,"en" => "let"
				)
			,"[pron]may:verb-aux" => array(
				"sv" => "kan"
				,"en" => "may"
				)
			,"shall:verb-aux" => array(
				"sv" => "ska"
				,"en" => "shall"
				)
			,"should:verb-aux" => array(
				"sv" => "ska"
				,"en" => "should"
				)
			,"want to:verb-aux" => array(
				"sv" => "vill"
				,"en" => "want::|s to"
				)
			,"[]you can:verb-aux" => array(
				"sv" => "du kan"
				,"en" => "you can"
				)
			,"you can:verb-aux" => array(
				"sv" => "kan du"
				,"en" => "you can"
				)
		);
	}	
} 
?>
