<?php 

// Defines constants
include("../../../../config.inc");

// Includes files
include("../../helpers.inc");
include("../db/db.inc");
include("../db/db_user.inc");
include("../db/db_admin.inc");
include("../db/db_forum_admin.inc");
include("../db/db_forum.inc");
include("../db/db_message.inc");
include("../db/db_workgroup.inc");
include("../db/db_error.inc");
include("../db/db_calendar.inc");
include("../db/db_vote.inc");
include("../db/db_prop.inc");
include("../db/db_delegate.inc");
include("../db/db_constituency.inc");
