<ul>
	<li>
		<h2>Medlemmar</h2>
		<ul>
			<li><a href="index.php?type=member&action=list">Se alla medlemmar</a></li>
			<li><a href="index.php?type=member&action=settings">Ändra inställningar</a></li>
			<li><a href="index.php?type=member&action=calendar">Kalender</a></li>
		</ul>
	</li>
	<li>
		<h2>Sök medlem</h2>
		<form method="post" class="sidebar_search_form" action="index.php?type=member&action=search">
			<input tabindex="101" type="text" value="" name="member_search_input" class="sidebar_search_input">
			<input tabindex="102" type="submit" class="sidebar_search_submit" value="Sök">
		</form>
	</li>
</ul>