<ul>
	<li>
		<h2>Valadministratör</h2>
		<ul>
			<li><a href="index.php?type=vote_admin&action=constituencylist">Lista valkretsar</li>
			<li><a href="index.php?type=vote_admin&action=create_constituency">Skapa ny valkrets</li>
			<li><a href="index.php?type=vote_admin&action=votelist">Lista omröstningar</li>
			<li><a href="index.php?type=vote_admin&action=create_new_vote">Skapa ny omröstning</li>
		</ul>
	</li>
</ul>