<form method="post" action="" class="text-editor">
	<fieldset>
		<legend class="create_new_topic">Skapa ny arbetsgrupp</legend>
		<label for "title">Namn på arbetsgrupp</label>
		<input type="text" name="title" id="title">
		<br>
		<label for "description">Beskrivning av arbetsgruppen</label>
		<textarea name="description" id="description" cols="60" rows="10"></textarea>
		<br>
		<input type="submit" value="Skapa">
	</fieldset>
</form>

<p>
Arbetsgrupper kan skapas av tre medlemmar tillsammans. Genom att fylla i formuläret ovan skapar du ett förslag till en arbetsgrupp. När tre medlemmar stödjer denna föreslagna arbetsgrupp kommer den att omvandlas till en riktig arbetsgrupp. </p>