<?php
namespace I18n; 

class translations 
{
	public static function create_translations() {
		return array(
			// UNCLASSIFIED
			"above" => array(
				"sv" => "ovan"
				,"en" => "above"
				)
			,"all" => array(
				"sv" => "alla"
				,"en" => "all"
				)
			,"the admittance of this candidate" => array(
				"sv" => "att denna kandidat upptas"
				,"en" => "the admittance of this candidate"
				)
			,"are" => array(
				"sv" => "är"
				,"en" => "are"
				)
			,"are appointed" => array(
				"sv" => "väljs"
				,"en" => "are appointed"
				)
			,"as" => array(
				"sv" => "som"
				,"en" => "as"
				)
			,"automatically" => array(
				"sv" => "automatiskt"
				,"en" => "automatically"
				)
			,"be given" => array(
				"sv" => "ges"
				,"en" => "be given"
				)
			,"become a" => array(
				"sv" => "bli"
				,"en" => "become a"
				)
			,"by filling the form" => array(
				"sv" => "genom att fylla i formuläret"
				,"en" => "by filling the form"
				)
			,"can be created" => array(
				"sv" => "kan skapas"
				,"en" => "can be created"
				)
			,"can be found" => array(
				"sv" => "finns"
				,"en" => "can be found"
				)
			,"candidate in" => array(
				"sv" => "kandidat in"
				,"en" => "candidate in"
				)
			,"currently the number of members is %d" => array(
				"sv" => "just nu är antalet medlemmar %d st"
				,"en" => "currently the number of members is"
				)
			,"do you really want to" => array(
				"sv" => "vill du verkligen"
				,"en" => "do you really want to"
				)
			,"forum topic-id" => array(
				"sv" => "forumtråds-ID"
				,"en" => "forum topic-ID"
				)
			,"have" => array(
				"sv" => "har"
				,"en" => "have"
				)
			,"hello" => array(
				"sv" => "hej"
				,"en" => "hello"
				)
			,"here" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"in the same way" => array(
				"sv" => "på samma sätt"
				,"en" => "in the same way"
				)
			,"is activated" => array(
				"sv" => "aktiveras"
				,"en" => "is activated"
				)
			,"is not possible" => array(
				"sv" => "går inte"
				,"en" => "is not possible"
				)
			,"it needs at least three members to be activated" => array(
				"sv" => "för att bli aktiv måste den ha minst tre medlemmar"
				,"en" => "it needs at least three members to be activated"
				)
			,"it will be transformed" => array(
				"sv" => "kommer den att omvandlas"
				,"en" => "it will be transformed"
				)
			,"its content has not yet been decided" => array(
				"sv" => "beslut om dess innehåll är ännu inte fattat"
				,"en" => "its content has not yet been decided"
				)
			,"just" => array(
				"sv" => "bara"
				,"en" => "just"
				)
			,"me" => array(
				"sv" => "mig"
				,"en" => "me"
				)
			,"name of" => array(
				"sv" => "namn på"
				,"en" => "name of"
				)
			,"no" => array(
				"sv" => "inga"
				,"en" => "no"
				)
			,"number of" => array(
				"sv" => "antal"
				,"en" => "number of"
				)
			,"superadmin" => array(
				"sv" => "superadmin"
				,"en" => "superadmin"
				)
			,"out" => array(
				"sv" => "ut"
				,"en" => "out"
				)
			,"that" => array(
				"sv" => "att"
				,"en" => "that"
				)
			,"this" => array(
				"sv" => "denna"
				,"en" => "this"
				)
			,"this is" => array(
				"sv" => "det här är"
				,"en" => "this is"
				)
			,"through" => array(
				"sv" => "via"
				,"en" => "through"
				)
			,"together" => array(
				"sv" => "tillsammans"
				,"en" => "together"
				)
			,"treasurer" => array(
				"sv" => "kassör"
				,"en" => "treasurer"
				)
			,"upcoming" => array(
				"sv" => "kommande"
				,"en" => "upcoming"
				)
			,"you create" => array(
				"sv" => "skapar du"
				,"en" => "you create"
				)
			,"your" => array(
				"sv" => "ditt"
				,"en" => "your"
				)
			,"vote (yes/no)" => array(
				"sv" => "votering (ja/nej)"
				,"en" => "vote (yes/no)"
				)
			,"vote status" => array(
				"sv" => "Omröstningens status"
				,"en" => "vote status"
				)
			,"welcome" => array(
				"sv" => "välkommen"
				,"en" => "welcome"
				)
			,"will be activated" => array(
				"sv" => "kommer aktiveras"
				,"en" => "will be activated"
				)
			,"when" => array(
				"sv" => "när"
				,"en" => "when"
				)

			// DEFINITE MARKERS
			,"the:definite" => array(
				"sv" => ""
				,"en" => "the"
				)
			,"the[adj|quant]:definite" => array(
				"sv" => "den|_t:_"
				,"en" => "the"
				)
			,"[]this:definite" => array(
				"sv" => "den|_t:_ här"
				,"en" => "this:__ese"
				)

			//INDEFINITE MODIFIERS
			,"to[verb]:indefinite" => array(
				"sv" => "att"
				,"en" => "to"
				)

			//CONJUNCTIONS
			,"and:conj" => array(
				"sv" => "och"
				,"en" => "and"
				)

			//PREPOSITIONS
			,"by:prep" => array(
				"sv" => "av"
				,"en" => "by"
				)
			,"[apply]for:prep" => array(
				"sv" => "om"
				,"en" => "for"
				)
			,"[candidate]for:prep" => array(
				"sv" => "till"
				,"en" => "for"
				)
			,"for:prep" => array(
				"sv" => "för"
				,"en" => "for"
				)
			,"[proposal]for:prep" => array(
				"sv" => "till"
				,"en" => "for"
				)
			,"in:prep" => array(
				"sv" => "i"
				,"en" => "in"
				)
			,"[member]of:prep" => array(
				"sv" => "i"
				,"en" => "of"
				)
			,"of:prep" => array(
				"sv" => "av"
				,"en" => "of"
				)
			,"to:prep" => array(
				"sv" => "till"
				,"en" => "to"
				)

			//PRONOUN: it
			,"it:pron-it" => array(
				"sv" => "den|det"
				,"en" => "it"
				)

			//PRONOUN
			,"you:pron" => array(
				"sv" => "du"
				,"en" => "you"
				)

			//QUANTIFIER
			,"%d:quant" => array(
				"sv" => "%d"
				,"en" => "%d"
				)
			,"three:quant" => array(
				"sv" => "tre"
				,"en" => "three"
				)
			,"a:quant" => array(
				"sv" => "en|_tt"
				,"en" => "a"
				)
			,"an:quant" => array(
				"sv" => "en|_tt"
				,"en" => "an"
				)

			//ADJECTIVES
			//singular_indefinite|non_type2:plural_indefinite:definite
			,"active:adj" => array(
				"sv" => "aktiv|t:a"
				,"en" => "active"
				)
			,"affirmed:adj" => array(
				"sv" => "beviljad|_t:e"
				,"en" => "affirmed"
				)
			,"continous:adj" => array(
				"sv" => "kontinuerlig|t:a"
				,"en" => "continous"
				)
			,"finished:adj" => array(
				"sv" => "avslutad|_t:e"
				,"en" => "finished"
				)
			,"late:adj" => array(
				"sv" => "sen|t:a:aste"
				,"en" => "late::st"
				)
			,"my:adj" => array(
				"sv" => "min|_tt:a"
				,"en" => "my"
				)
			,"new:adj" => array(
				"sv" => "ny|tt:a"
				,"en" => "new"
				)
			,"old:adj" => array(
				"sv" => "gammal|t:___la"
				,"en" => "old"
				)
			,"ongoing:adj" => array(
				"sv" => "pågående"
				,"en" => "ongoing"
				)
			,"open:adj" => array(
				"sv" => "öppen|_t:__na"
				,"en" => "open"
				)
			,"time limited:adj" => array(
				"sv" => "tidsbegränsad|_t:e"
				,"en" => "time limited"
				)

			//VERBS
			//imperative:infinitive:present:perfect:perfect particip
			,"administrate:verb" => array(
				"sv" => "administrera::r:t:(d|_t:e)"
				,"en" => "administrate::|s:d:(d)"
				)
			,"apply:verb" => array(
				"sv" => "ansök:a:er:t"
				,"en" => "apply::|_ies:_ied"
				)
			,"cancel:verb" => array(
				"sv" => "avbryt"
				,"en" => "cancel"
				)
			,"change:verb" => array(
				"sv" => "ändra"
				,"en" => "change"
				)
			,"close:verb" => array(
				"sv" => "stäng:a:er:t:(d|_t:a)"
				,"en" => "close::|s:d:(d)"
				)
			,"create:verb" => array(
				"sv" => "skapa::r:t:(d|_t:e)"
				,"en" => "create::|s:d:(d)"
				)
			,"discontinue:verb" => array(
				"sv" => "avsluta"
				,"en" => "discontinue"
				)
			,"edit:verb" => array(
				"sv" => "redigera::r:t:(d|_t:e)"
				,"en" => "edit::|s:ed:(ed)"
				)
			,"exclude:verb" => array(
				"sv" => "uteslut:a:er:it:(en|_t:__na)"
				,"en" => "exclude::|s:d:(d)"
				)
			,"finish:verb" => array(
				"sv" => "avsluta"
				,"en" => "finish"
				)
			,"finishes:verb" => array(
				"sv" => "slutar"
				,"en" => "finishes"
				)
			,"handle:verb" => array(
				"sv" => "hantera"
				,"en" => "handle"
				)
			,"is:verb" => array(
				"sv" => "var:a:___är:it:(ande)"
				,"en" => "be::__is:en:(ing)"
				)
			,"leave:verb" => array(
				"sv" => "lämna"
				,"en" => "leave"
				)
			,"list:verb" => array(
				"sv" => "lista"
				,"en" => "list"
				)
			,"login:verb" => array(
				"sv" => "logga in"
				,"en" => "login"
				)
			,"logout:verb" => array(
				"sv" => "logga ut"
				,"en" => "logout"
				)
			,"propose:verb" => array(
				"sv" => "föreslå::r:_agit:(_agen|_t:__na)"
				,"en" => "propose::|s:d:(d)"
				)				
			,"remember:verb" => array(
				"sv" => "kom ihåg"
				,"en" => "remember"
				)				
			,"resume:verb" => array(
				"sv" => "återuppta"
				,"en" => "resume"
				)				
			,"revoke:verb" => array(
				"sv" => "återta"
				,"en" => "revoke"
				)				
			,"search:verb" => array(
				"sv" => "sök"
				,"en" => "search"
				)
			,"see:verb" => array(
				"sv" => "se"
				,"en" => "see"
				)
			,"send:verb" => array(
				"sv" => "skicka::r:t:(d|_t:e)"
				,"en" => "send::|s:_t:(_t)"
				)
			,"support:verb" => array(
				"sv" => "stöd:ja:jer"
				,"en" => "support::|s"
				)
			,"stop supporting:verb" => array(
				"sv" => "sluta stödja"
				,"en" => "stop supporting"
				)
			,"transform:verb" => array(
				"sv" => "gör om"
				,"en" => "transform"
				)
			,"undo:verb" => array(
				"sv" => "ångra"
				,"en" => "undo"
				)
			,"view:verb" => array(
				"sv" => "visa"
				,"en" => "view"
				)
			,"vote for:verb" => array(
				"sv" => "rösta för"
				,"en" => "vote for"
				)
			,"want to:verb" => array(
				"sv" => "vill"
				,"en" => "want::|s to"
				)
			,"will:verb" => array(
				"sv" => "kommer"
				,"en" => "will"
				)
			,"write:verb" => array(
				"sv" => "skriv"
				,"en" => "write"
				)
			
			//NOUNS
			//singular_indefinite:plural_indefinite:singular_definite:plural_definite
			,"active vote:noun1" => array(
				"sv" => "pågående omröstning:ar"
				,"en" => "active vote:s"
				)
			,"admin:noun1" => array(
				"sv" => "admin:istratörer"
				,"en" => "admin:istrators"
				)
			,"administrator:noun1" => array(
				"sv" => "administratör:er"
				,"en" => "administrator:s"
				)
			,"application:noun1" => array(
				"sv" => "ansökning:ar"
				,"en" => "application:s"
				)
			,"authorisation:noun1" => array(
				"sv" => "behörighet:er"
				,"en" => "authorisation:s"
				)
			,"budget:noun1" => array(
				"sv" => "budget:ar:-"
				,"en" => "budget:s"
				)
			,"calendar:noun1" => array(
				"sv" => "kalender:__rar"
				,"en" => "calendar:s"
				)
			,"candidate:noun1" => array(
				"sv" => "kandidat:er"
				,"en" => "candidate:s"
				)
			,"category:noun1" => array(
				"sv" => "kategori:er"
				,"en" => "category:_ies"
				)
			,"change:noun1" => array(
				"sv" => "förändring:ar"
				,"en" => "change:s"
				)
			,"constituency:noun1" => array(
				"sv" => "valkrets:ar:-"
				,"en" => "constituency:_ies"
				)
			,"delegate:noun1" => array(
				"sv" => "delegat:er:-"
				,"en" => "delegate:s"
				)
			,"delegation:noun1" => array(
				"sv" => "delegering:ar"
				,"en" => "delegation:s"
				)
			,"description:noun1" => array(
				"sv" => "beskrivning:ar"
				,"en" => "description:s"
				)
			,"exclusion:noun1" => array(
				"sv" => "uteslutning"
				,"en" => "exclusion"
				)
			,"forum admin:noun1" => array(
				"sv" => "forumadministratör:er"
				,"en" => "forum admin:s"
				)
			,"front page:noun1" => array(
				"sv" => "första-sida"
				,"en" => "front page"
				)
			,"group:noun1" => array(
				"sv" => "grupp:er:-"
				,"en" => "group:s"
				)
			,"inbox:noun1" => array(
				"sv" => "inbox:ar"
				,"en" => "inbox:es"
				)
			,"median:noun1" => array(
				"sv" => "median:er:-"
				,"en" => "median:s"
				)
			,"member:noun1" => array(
				"sv" => "medlem:mar:men:na"
				,"en" => "member:s"
				)
			,"member admin:noun1" => array(
				"sv" => "medlemsansvarig:a"
				,"en" => "member admin:s"
				)
			,"profile:noun1" => array(
				"sv" => "profil:er"
				,"en" => "profile:s"
				)
			,"outbox:noun1" => array(
				"sv" => "skickade"
				,"en" => "outbox"
				)
			,"priority:noun1" => array(
				"sv" => "prioritet:er:-s"
				,"en" => "priority:_ies"
				)
			,"proposition:noun1" => array(
				"sv" => "proposition:er"
				,"en" => "proposition:s"
				)
			,"setting:noun1" => array(
				"sv" => "inställning:ar"
				,"en" => "setting:s"
				)
			,"supporter:noun1" => array(
				"sv" => "stödjare::n:_na"
				,"en" => "supporter:s"
				)
			,"user:noun1" => array(
				"sv" => "användare"
				,"en" => "user:s"
				)
			,"time:noun1" => array(
				"sv" => "tidpunkt:er"
				,"en" => "time:s"
				)
			,"vote:noun1" => array(
				"sv" => "omröstning:ar:en:arna"
				,"en" => "vote:s"
				)
			,"vote admin:noun1" => array(
				"sv" => "valadministratör:er"
				,"en" => "vote admin:s"
				)
			,"workgroup:noun1" => array(
				"sv" => "arbetsgrupp:er:en:na"
				,"en" => "workgroup:s"
				)

			//NOUNS, variation 2
			,"alternative:noun2" => array(
				"sv" => "alternativ"
				,"en" => "alternative:s"
				)
			,"candidate election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "candidate election:s"
				)
			,"election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "election:s"
				)
			,"forum:noun2" => array(
				"sv" => "forum"
				,"en" => "forum:s"
				)
			,"membership:noun2" => array(
				"sv" => "medlemskap"
				,"en" => "membership"
				)
			,"message:noun2" => array(
				"sv" => "meddelande:n"
				,"en" => "message:s"
				)
			,"password:noun2" => array(
				"sv" => "lösenord"
				,"en" => "password:s"
				)
			,"post:noun2" => array(
				"sv" => "inlägg::et:en"
				,"en" => "post:s"
				)
			,"proposal:noun2" => array(
				"sv" => "förslag::et:en"
				,"en" => "proposal:s"
				)
			,"username:noun2" => array(
				"sv" => "användarnamn"
				,"en" => "username:s"
				)
		);
	}	
} 
?>
