<?php
namespace I18n; 

class translations 
{
	public static function create_translations() {
		return array(
			// UNCLASSIFIED
			"after" => array(
				"sv" => "efter att"
				,"en" => "after"
				)
			,"after the vote has been created" => array(
				"sv" => "efter att omröstningen har skapats"
				,"en" => "after the vote has been created"
				)
			,"all" => array(
				"sv" => "alla"
				,"en" => "all"
				)
			,"all those" => array(
				"sv" => "alla"
				,"en" => "all those"
				)
			,"alphabetic" => array(
				"sv" => "alfabetisk"
				,"en" => "alphabetic"
				)
			,"also" => array(
				"sv" => "också"
				,"en" => "also"
				)
			,"also means" => array(
				"sv" => "innebär också"
				,"en" => "also means"
				)
			,"are" => array(
				"sv" => "är"
				,"en" => "are"
				)
			,"are appointed" => array(
				"sv" => "väljs"
				,"en" => "are appointed"
				)
			,"as" => array(
				"sv" => "som"
				,"en" => "as"
				)
			,"automatically" => array(
				"sv" => "automatiskt"
				,"en" => "automatically"
				)
			,"back" => array(
				"sv" => "tillbaka"
				,"en" => "back"
				)
			,"be given" => array(
				"sv" => "ges"
				,"en" => "be given"
				)
			,"be seen" => array(
				"sv" => "ses"
				,"en" => "be seen"
				)
			,"become a" => array(
				"sv" => "bli"
				,"en" => "become a"
				)
			,"by filling the form" => array(
				"sv" => "genom att fylla i formuläret"
				,"en" => "by filling the form"
				)
			,"can be created" => array(
				"sv" => "kan skapas"
				,"en" => "can be created"
				)
			,"can be found" => array(
				"sv" => "finns"
				,"en" => "can be found"
				)
			,"candidate in" => array(
				"sv" => "kandidat in"
				,"en" => "candidate in"
				)
			,"currently the number of members is %d" => array(
				"sv" => "just nu är antalet medlemmar %d st"
				,"en" => "currently the number of members is"
				)
			,"delegate voting closes" => array(
				"sv" => "delegatröstning avslutas"
				,"en" => "delegate voting closes"
				)
			,"directly" => array(
				"sv" => "direkt"
				,"en" => "directly"
				)
			,"do you really want to" => array(
				"sv" => "vill du verkligen"
				,"en" => "do you really want to"
				)
			,"do you still want to continue" => array(
				"sv" => "vill du fortsätta ändå"
				,"en" => "do you still want to continue"
				)
			,"doesn't support" => array(
				"sv" => "stöder ej"
				,"en" => "doesn't support"
				)
			,"even" => array(
				"sv" => "även"
				,"en" => "even"
				)
			,"for which you have registerered your delegacy" => array(
				"sv" => "som du angivit för din delegat"
				,"en" => "for which you have registerered your delegacy"
				)
			,"forum topic-id" => array(
				"sv" => "forumtråds-ID"
				,"en" => "forum topic-ID"
				)
			,"found" => array(
				"sv" => "funna"
				,"en" => "found"
				)
			,"half" => array(
				"sv" => "halva"
				,"en" => "half"
				)
			,"has been cast" => array(
				"sv" => "är lagd"
				,"en" => "has been cast"
				)
			,"has voted" => array(
				"sv" => "röstat"
				,"en" => "has voted"
				)
			,"has voted for you" => array(
				"sv" => "har röstat åt dig"
				,"en" => "has voted for you"
				)
			,"have" => array(
				"sv" => "har"
				,"en" => "have"
				)
			,"have cast your own ballot" => array(
				"sv" => "har lagt din egen röst"
				,"en" => "have cast your own ballot"
				)
			,"have let your delegate vote" => array(
				"sv" => "har låtit din delegat rösta"
				,"en" => "have let your delegate vote"
				)
			,"hello" => array(
				"sv" => "hej"
				,"en" => "hello"
				)
			,"here" => array(
				"sv" => "här"
				,"en" => "here"
				)
			,"if" => array(
				"sv" => "om"
				,"en" => "if"
				)
			,"if you want to" => array(
				"sv" => "vill du"
				,"en" => "if you want to"
				)
			,"in case" => array(
				"sv" => "ifall"
				,"en" => "in case"
				)
			,"in the same way" => array(
				"sv" => "på samma sätt"
				,"en" => "in the same way"
				)
			,"in which" => array(
				"sv" => "inom vilka"
				,"en" => "in which"
				)
			,"instead of" => array(
				"sv" => "istället för"
				,"en" => "instead of"
				)
			,"is activated" => array(
				"sv" => "aktiveras"
				,"en" => "is activated"
				)
			,"is not possible" => array(
				"sv" => "går inte"
				,"en" => "is not possible"
				)
			,"it cannot be removed" => array(
				"sv" => "kan det inte tas bort"
				,"en" => "it cannot be removed"
				)
			,"it continues until it is ended through a new yes/no vote" => array(
				"sv" => "den fortsätter tills en votering bestämmer att den ska avslutas"
				,"en" => "it continues until it is ended through a new yes/no vote"
				)
			,"it finished" => array(
				"sv" => "den avslutades"
				,"en" => "it finished"
				)
			,"it is possible" => array(
				"sv" => "finns möjligheten"
				,"en" => "it is possible"
				)
			,"it needs at least three members to be activated" => array(
				"sv" => "för att bli aktiv måste den ha minst tre medlemmar"
				,"en" => "it needs at least three members to be activated"
				)
			,"it to be subject for vote is" => array(
				"sv" => "att den ska godkännas och gå vidare till omröstning är"
				,"en" => "it to be subject for vote is"
				)
			,"it will be transformed" => array(
				"sv" => "kommer den att omvandlas"
				,"en" => "it will be transformed"
				)
			,"its content has not yet been decided" => array(
				"sv" => "beslut om dess innehåll är ännu inte fattat"
				,"en" => "its content has not yet been decided"
				)
			,"just" => array(
				"sv" => "bara"
				,"en" => "just"
				)
			,"me" => array(
				"sv" => "mig"
				,"en" => "me"
				)
			,"name of" => array(
				"sv" => "namn på"
				,"en" => "name of"
				)
			,"necessary" => array(
				"sv" => "nödvändigt"
				,"en" => "necessary"
				)
			,"no" => array(
				"sv" => "nej"
				,"en" => "no"
				)
			,"not yet" => array(
				"sv" => "ännu inte"
				,"en" => "not yet"
				)
			,"number of" => array(
				"sv" => "antal"
				,"en" => "number of"
				)
			,"on proposition" => array(
				"sv" => "på propositionen"
				,"en" => "on proposition"
				)
			,"only" => array(
				"sv" => "bara"
				,"en" => "only"
				)
			,"out" => array(
				"sv" => "ut"
				,"en" => "out"
				)
			,"other than" => array(
				"sv" => "annat än"
				,"en" => "other than"
				)
			,"personally" => array(
				"sv" => "personligt"
				,"en" => "personally"
				)
			,"proposition created" => array(
				"sv" => "propositionen skapad"
				,"en" => "proposition created"
				)
			,"proposition's" => array(
				"sv" => "propositions"
				,"en" => "proposition's"
				)
			,"register as candidate for" => array(
				"sv" => "anmäl dig som kandidat i"
				,"en" => "register as candidate for"
				)
			,"registered as a delegate" => array(
				"sv" => "registrerad som delegat"
				,"en" => "registered as a delegate"
				)
			,"revoke ballot" => array(
				"sv" => "ångra röst"
				,"en" => "revoke ballot"
				)
			,"so" => array(
				"sv" => "så"
				,"en" => "so"
				)
			,"stop supporting" => array(
				"sv" => "sluta stödja"
				,"en" => "stop supporting"
				)
			,"superadmin" => array(
				"sv" => "superadmin"
				,"en" => "superadmin"
				)
			,"supporting" => array(
				"sv" => "stöder"
				,"en" => "supporting"
				)
			,"that" => array(
				"sv" => "att"
				,"en" => "that"
				)
			,"the admittance of this candidate" => array(
				"sv" => "att denna kandidat upptas"
				,"en" => "the admittance of this candidate"
				)
			,"for the particular issue" => array(
				"sv" => "i den frågan"
				,"en" => "från the particular issue"
				)
			,"the possibility to vote closed" => array(
				"sv" => "stängdes möjligheten att rösta"
				,"en" => "the possibility to vote closed"
				)
			,"the possibility to vote closes" => array(
				"sv" => "stänger möjligheten att rösta"
				,"en" => "the possibility to vote closes"
				)
			,"their vote" => array(
				"sv" => "sin röst"
				,"en" => "their vote"
				)
			,"this" => array(
				"sv" => "denna"
				,"en" => "this"
				)
			,"this is" => array(
				"sv" => "det här är"
				,"en" => "this is"
				)
			,"this is not appropriate" => array(
				"sv" => "detta inte är lämpligt"
				,"en" => "this is not appropriate"
				)
			,"this means" => array(
				"sv" => "det innebär"
				,"en" => "this means"
				)
			,"those" => array(
				"sv" => "de"
				,"en" => "those"
				)
			,"through" => array(
				"sv" => "via"
				,"en" => "through"
				)
			,"to be subject for" => array(
				"sv" => "för att gå vidare och bli"
				,"en" => "to be subject for"
				)
			,"to stop supporting" => array(
				"sv" => "för att sluta stödja"
				,"en" => "to stop supporting"
				)
			,"together" => array(
				"sv" => "tillsammans"
				,"en" => "together"
				)
			,"treasurer" => array(
				"sv" => "kassör"
				,"en" => "treasurer"
				)
			,"upcoming" => array(
				"sv" => "kommande"
				,"en" => "upcoming"
				)
			,"vote (yes/no)" => array(
				"sv" => "votering (ja/nej)"
				,"en" => "vote (yes/no)"
				)
			,"vote as delegate" => array(
				"sv" => "rösta som delegat"
				,"en" => "vote as delegate"
				)
			,"vote closes" => array(
				"sv" => "omröstningen avslutas"
				,"en" => "vote closes"
				)
			,"vote started" => array(
				"sv" => "Omröstningen startad"
				,"en" => "vote started"
				)
			,"vote status" => array(
				"sv" => "Omröstningens status"
				,"en" => "vote status"
				)
			,"was found" => array(
				"sv" => "hittades"
				,"en" => "was found"
				)
			,"welcome" => array(
				"sv" => "välkommen"
				,"en" => "welcome"
				)
			,"will be activated" => array(
				"sv" => "kommer aktiveras"
				,"en" => "will be activated"
				)
			,"will be completely deleted" => array(
				"sv" => "kommer att raderas fullständigt"
				,"en" => "will be completely deleted"
				)
			,"when" => array(
				"sv" => "när"
				,"en" => "when"
				)
			,"whereof" => array(
				"sv" => "varav"
				,"en" => "whereof"
				)
			,"who" => array(
				"sv" => "som"
				,"en" => "who"
				)
			,"yes" => array(
				"sv" => "ja"
				,"en" => "yes"
				)
			,"you create" => array(
				"sv" => "skapar du"
				,"en" => "you create"
				)
			,"you don't have to vote as delegate" => array(
				"sv" => "behöver du inte rösta som delegat"
				,"en" => "you don't have to vote as delegate"
				)
			,"you have cast" => array(
				"sv" => "du har själv lagt"
				,"en" => "you have cast"
				)
			,"you press" => array(
				"sv" => "trycker du på"
				,"en" => "you press"
				)
			,"[]you vote" => array(
				"sv" => "du röstar"
				,"en" => "you vote"
				)
			,"you vote" => array(
				"sv" => "röstar du"
				,"en" => "you vote"
				)
			,"you vote for" => array(
				"sv" => "du röstar för"
				,"en" => "you vote for"
				)
			,"you vote and support propositions" => array(
				"sv" => "röstar du och stödjer propositioner"
				,"en" => "you vote and support propositions"
				)

			// GENITIVE
			,"'s:genitive" => array(
				"sv" => "s"
				,"en" => "'s"
				)
			,"':genitive" => array(
				"sv" => ""
				,"en" => "'"
				)

			// DEFINITE MARKERS
			,"the:definite" => array(
				"sv" => ""
				,"en" => "the"
				)
			,"the[adj|quant]:definite" => array(
				"sv" => "den|_t:_"
				,"en" => "the"
				)
			,"[]this:definite" => array(
				"sv" => "den|_t:_ här"
				,"en" => "this:__ese"
				)

			//INDEFINITE MODIFIERS
			,"[]to:indefinite" => array(
				"sv" => "för att"
				,"en" => "to"
				)
			,"to[verb|adverb]:indefinite" => array(
				"sv" => "att"
				,"en" => "to"
				)

			//CONJUNCTIONS
			,"and:conj" => array(
				"sv" => "och"
				,"en" => "and"
				)
			,"or:conj" => array(
				"sv" => "eller"
				,"en" => "or"
				)

			//PREPOSITIONS
			,"above:prep" => array(
				"sv" => "ovan"
				,"en" => "above"
				)
			,"below:prep" => array(
				"sv" => "nedan"
				,"en" => "below"
				)
			,"by:prep" => array(
				"sv" => "av"
				,"en" => "by"
				)
			,"[apply]for:prep" => array(
				"sv" => "om"
				,"en" => "for"
				)
			,"[candidate]for:prep" => array(
				"sv" => "till"
				,"en" => "for"
				)
			,"for:prep" => array(
				"sv" => "för"
				,"en" => "for"
				)
			,"[proposal]for:prep" => array(
				"sv" => "till"
				,"en" => "for"
				)
			,"in:prep" => array(
				"sv" => "i"
				,"en" => "in"
				)
			,"[member]of:prep" => array(
				"sv" => "i"
				,"en" => "of"
				)
			,"of:prep" => array(
				"sv" => "av"
				,"en" => "of"
				)
			,"on:prep" => array(
				"sv" => "på"
				,"en" => "on"
				)
			,"to:prep" => array(
				"sv" => "till"
				,"en" => "to"
				)
			,"with:prep" => array(
				"sv" => "med"
				,"en" => "with"
				)

			//PRONOUN
			,"[to]you:pron" => array(
				"sv" => "dig"
				,"en" => "you"
				)
			,"you:pron" => array(
				"sv" => "du"
				,"en" => "you"
				)

			//PRONOUN: it
			,"it:pron-it" => array(
				"sv" => "den|det"
				,"en" => "it"
				)

			//POSSESSIVE PRONOUN
			,"your:pron-poss" => array(
				"sv" => "din|_tt:a"
				,"en" => "your"
				)

			//QUANTIFIER
			,"%d:quant" => array(
				"sv" => "%d"
				,"en" => "%d"
				)
			,"more:quant" => array(
				"sv" => "fler"
				,"en" => "more"
				)
			,"no[noun-singular]:quant" => array(
				"sv" => "ingen"
				,"en" => "no"
				)
			,"no[noun-plural]:quant" => array(
				"sv" => "inga"
				,"en" => "no"
				)
			,"other[noun-plural]:quant" => array(
				"sv" => "andra"
				,"en" => "other"
				)
			,"three:quant" => array(
				"sv" => "tre"
				,"en" => "three"
				)
			,"a:quant" => array(
				"sv" => "en|_tt"
				,"en" => "a"
				)
			,"an:quant" => array(
				"sv" => "en|_tt"
				,"en" => "an"
				)

			//ADVERBS
			,"temporarily:adverb" => array(
				"sv" => "tillfälligt"
				,"en" => "temporarily"
				)

			//ADJECTIVES
			//singular_indefinite|non_type2:plural_indefinite:definite
			,"active:adj" => array(
				"sv" => "aktiv|t:a"
				,"en" => "active"
				)
			,"affirmed:adj" => array(
				"sv" => "beviljad|_t:e"
				,"en" => "affirmed"
				)
			,"continous:adj" => array(
				"sv" => "kontinuerlig|t:a"
				,"en" => "continous"
				)
			,"current:adj" => array(
				"sv" => "aktuell|t:a"
				,"en" => "current"
				)
			,"finished:adj" => array(
				"sv" => "avslutad|_t:e"
				,"en" => "finished"
				)
			,"late:adj" => array(
				"sv" => "sen|t:a:aste"
				,"en" => "late::st"
				)
			,"my:adj" => array(
				"sv" => "min|_tt:a"
				,"en" => "my"
				)
			,"new:adj" => array(
				"sv" => "ny|tt:a"
				,"en" => "new"
				)
			,"old:adj" => array(
				"sv" => "gammal|t:___la"
				,"en" => "old"
				)
			,"ongoing:adj" => array(
				"sv" => "pågående"
				,"en" => "ongoing"
				)
			,"open:adj" => array(
				"sv" => "öppen|_t:__na"
				,"en" => "open"
				)
			,"public:adj" => array(
				"sv" => "offentlig|t:a"
				,"en" => "public"
				)
			,"sufficient:adj" => array(
				"sv" => "tillräcklig|t:a"
				,"en" => "sufficient"
				)
			,"time limited:adj" => array(
				"sv" => "tidsbegränsad|_t:e"
				,"en" => "time limited"
				)

			//VERBS
			//imperative:infinitive:present:perfect:perfect particip
			,"abstain:verb" => array(
				"sv" => "avstår"
				,"en" => "abstain"
				)
			,"add:verb" => array(
				"sv" => "lägg till"
				,"en" => "add"
				)
			,"administrate:verb" => array(
				"sv" => "administrera::r:t:(d|_t:e)"
				,"en" => "administrate::|s:d:(d)"
				)
			,"apply:verb" => array(
				"sv" => "ansök:a:er:t"
				,"en" => "apply::|_ies:_ied"
				)
			,"be:verb" => array(
				"sv" => "var:a:___är:it:(ande)"
				,"en" => "be::__are|___is:en:(ing)"
				)
			,"become:verb" => array(
				"sv" => "bli::r:vit"
				,"en" => "become::|s:___ame"
				)
			,"cancel:verb" => array(
				"sv" => "avbryt"
				,"en" => "cancel"
				)
			,"candidate:verb" => array(
				"sv" => "kandidera"
				,"en" => "candidate"
				)
			,"cast:verb" => array(
				"sv" => "lägg::er:___agt:(___agd|_t:a)"
				,"en" => "cast::|s"
				)
			,"change:verb" => array(
				"sv" => "ändra"
				,"en" => "change"
				)
			,"check:verb" => array(
				"sv" => "markera::r:t:(d|_t:e)"
				,"en" => "check::|s:ed:(ed)"
				)
			,"choose:verb" => array(
				"sv" => "välj:a:er:___alt:(___ald|_t:a)"
				,"en" => "choose::|s:d:(n)"
				)
			,"click:verb" => array(
				"sv" => "klicka::r:t"
				,"en" => "click::|s:ed"
				)
			,"close:verb" => array(
				"sv" => "stäng:a:er:t:(d|_t:a)"
				,"en" => "close::|s:d:(d)"
				)
			,"create:verb" => array(
				"sv" => "skapa::r:t:(d|_t:e)"
				,"en" => "create::|s:d:(d)"
				)
			,"deactivate:verb" => array(
				"sv" => "avaktivera::r:t:(d|_t:e)"
				,"en" => "deactivate::|s:d:(d)"
				)
			,"delegate:verb" => array(
				"sv" => "delegera::r:t:(d|_t:e)"
				,"en" => "delegate::|s:d:(d)"
				)
			,"delete:verb" => array(
				"sv" => "radera::r:t:(d|_t:e)"
				,"en" => "delete::|s:d:(d)"
				)
			,"demote:verb" => array(
				"sv" => "mota::r:t:(d|_t:e)"
				,"en" => "demote::|s:d:(d)"
				)				
			,"discontinue:verb" => array(
				"sv" => "avsluta"
				,"en" => "discontinue"
				)
			,"edit:verb" => array(
				"sv" => "redigera::r:t:(d|_t:e)"
				,"en" => "edit::|s:ed:(ed)"
				)
			,"exclude:verb" => array(
				"sv" => "uteslut:a:er:it:(en|_t:__na)"
				,"en" => "exclude::|s:d:(d)"
				)
			,"finish:verb" => array(
				"sv" => "avsluta"
				,"en" => "finish"
				)
			,"finishes:verb" => array(
				"sv" => "slutar"
				,"en" => "finishes"
				)
			,"handle:verb" => array(
				"sv" => "hantera"
				,"en" => "handle"
				)
			,"have:verb" => array(
				"sv" => "ha::r:ft"
				,"en" => "have::|__s:__d"
				)
			,"leave:verb" => array(
				"sv" => "lämna"
				,"en" => "leave"
				)
			,"list:verb" => array(
				"sv" => "lista"
				,"en" => "list"
				)
			,"login:verb" => array(
				"sv" => "logga in"
				,"en" => "login"
				)
			,"logout:verb" => array(
				"sv" => "logga ut"
				,"en" => "logout"
				)
			,"note:verb" => array(
				"sv" => "notera"
				,"en" => "note"
				)
			,"order:verb" => array(
				"sv" => "rangordna"
				,"en" => "order"
				)
			,"press:verb" => array(
				"sv" => "tryck på"
				,"en" => "press"
				)
			,"promote:verb" => array(
				"sv" => "främja::r:t:(d|_t:e)"
				,"en" => "promote::|s:d:(d)"
				)				
			,"propose:verb" => array(
				"sv" => "föreslå::r:_agit:(_agen|_t:__na)"
				,"en" => "propose::|s:d:(d)"
				)				
			,"reach:verb" => array(
				"sv" => "uppnå::r:tt"
				,"en" => "reach::|es:ed"
				)				
			,"register:verb" => array(
				"sv" => "registrera::r:t:(d|_t:e)"
				,"en" => "register::|s:ed:(ed)"
				)				
			,"remember:verb" => array(
				"sv" => "kom ihåg"
				,"en" => "remember"
				)				
			,"remove:verb" => array(
				"sv" => "ta::r:git bort"
				,"en" => "remove::|s:d"
				)				
			,"resume:verb" => array(
				"sv" => "återuppta"
				,"en" => "resume"
				)				
			,"revoke:verb" => array(
				"sv" => "återta"
				,"en" => "revoke"
				)				
			,"search:verb" => array(
				"sv" => "sök"
				,"en" => "search"
				)
			,"see:verb" => array(
				"sv" => "se"
				,"en" => "see"
				)
			,"send:verb" => array(
				"sv" => "skicka::r:t:(d|_t:e)"
				,"en" => "send::|s:_t:(_t)"
				)
			,"support:verb" => array(
				"sv" => "stöd:ja:jer"
				,"en" => "support::|s"
				)
			,"transform:verb" => array(
				"sv" => "gör om"
				,"en" => "transform"
				)
			,"undo:verb" => array(
				"sv" => "ångra"
				,"en" => "undo"
				)
			,"update:verb" => array(
				"sv" => "uppdatera"
				,"en" => "update"
				)
			,"view:verb" => array(
				"sv" => "visa"
				,"en" => "view"
				)
			,"vote:verb" => array(
				"sv" => "rösta"
				,"en" => "vote"
				)
			,"[]vote for:verb" => array(
				"sv" => "rösta för"
				,"en" => "vote for"
				)
			,"voted:verb" => array(
				"sv" => "röstat"
				,"en" => "voted"
				)
			,"will:verb" => array(
				"sv" => "kommer"
				,"en" => "will"
				)
			,"withdraw:verb" => array(
				"sv" => "dra::r:git tillbaka"
				,"en" => "withdraw::|s:n"
				)
			,"write:verb" => array(
				"sv" => "skriv"
				,"en" => "write"
				)

			//AUXILIARY VERBS
			//imperative:infinitive:present:perfect
			,"be able to:verb-aux" => array(
				"sv" => "kunna"
				,"en" => "be able to"
				)
			,"can:verb-aux" => array(
				"sv" => "kan"
				,"en" => "can"
				)
			,"let:verb-aux" => array(
				"sv" => "låta"
				,"en" => "let"
				)
			,"may:verb-aux" => array(
				"sv" => "kan"
				,"en" => "may"
				)
			,"want to:verb-aux" => array(
				"sv" => "vill"
				,"en" => "want::|s to"
				)
			,"shall:verb-aux" => array(
				"sv" => "ska"
				,"en" => "shall"
				)
			,"[]you can:verb-aux" => array(
				"sv" => "du kan"
				,"en" => "you can"
				)
			,"you can:verb-aux" => array(
				"sv" => "kan du"
				,"en" => "you can"
				)

			//NOUNS
			//singular_indefinite:plural_indefinite:singular_definite:plural_definite
			,"active vote:noun1" => array(
				"sv" => "pågående omröstning:ar"
				,"en" => "active vote:s"
				)
			,"admin:noun1" => array(
				"sv" => "admin:istratörer"
				,"en" => "admin:istrators"
				)
			,"administrator:noun1" => array(
				"sv" => "administratör:er"
				,"en" => "administrator:s"
				)
			,"application:noun1" => array(
				"sv" => "ansökning:ar"
				,"en" => "application:s"
				)
			,"authorisation:noun1" => array(
				"sv" => "behörighet:er"
				,"en" => "authorisation:s"
				)
			,"ballot:noun1" => array(
				"sv" => "röst:er:en:na"
				,"en" => "ballot:s"
				)
			,"box:noun1" => array(
				"sv" => "ruta:_or:n:na"
				,"en" => "box:es"
				)
			,"budget:noun1" => array(
				"sv" => "budget:ar:-"
				,"en" => "budget:s"
				)
			,"button:noun1" => array(
				"sv" => "knapp:ar:en:na"
				,"en" => "button:s"
				)
			,"calendar:noun1" => array(
				"sv" => "kalender:__rar"
				,"en" => "calendar:s"
				)
			,"candidacy:noun1" => array(
				"sv" => "kandidatur:er:en:na:-"
				,"en" => "candidacy:_ies"
				)
			,"candidate:noun1" => array(
				"sv" => "kandidat:er:en:na:-"
				,"en" => "candidate:s"
				)
			,"caption:noun1" => array(
				"sv" => "rubrik:er:en:na"
				,"en" => "caption:s"
				)
			,"category:noun1" => array(
				"sv" => "kategori:er"
				,"en" => "category:_ies"
				)
			,"change:noun1" => array(
				"sv" => "förändring:ar"
				,"en" => "change:s"
				)
			,"constituency:noun1" => array(
				"sv" => "valkrets:ar:en:na:-"
				,"en" => "constituency:_ies"
				)
			,"debate:noun1" => array(
				"sv" => "debatt:er"
				,"en" => "debate:s"
				)
			,"delegate:noun1" => array(
				"sv" => "delegat:er:-"
				,"en" => "delegate:s"
				)
			,"delegate setting:noun1" => array(
				"sv" => "delegatinställning:ar"
				,"en" => "delegate setting:s"
				)
			,"delegation:noun1" => array(
				"sv" => "delegering:ar"
				,"en" => "delegation:s"
				)
			,"description:noun1" => array(
				"sv" => "beskrivning:ar"
				,"en" => "description:s"
				)
			,"exclusion:noun1" => array(
				"sv" => "uteslutning"
				,"en" => "exclusion"
				)
			,"forum admin:noun1" => array(
				"sv" => "forumadministratör:er"
				,"en" => "forum admin:s"
				)
			,"front page:noun1" => array(
				"sv" => "första-sida"
				,"en" => "front page"
				)
			,"group:noun1" => array(
				"sv" => "grupp:er:-"
				,"en" => "group:s"
				)
			,"inbox:noun1" => array(
				"sv" => "inbox:ar"
				,"en" => "inbox:es"
				)
			,"individual:noun1" => array(
				"sv" => "privatperson"
				,"en" => "individual"
				)
			,"link:noun1" => array(
				"sv" => "länk:ar"
				,"en" => "link:es"
				)
			,"median:noun1" => array(
				"sv" => "median:er:-"
				,"en" => "median:s"
				)
			,"member:noun1" => array(
				"sv" => "medlem:mar:men:na"
				,"en" => "member:s"
				)
			,"member admin:noun1" => array(
				"sv" => "medlemsansvarig:a"
				,"en" => "member admin:s"
				)
			,"phrase:noun1" => array(
				"sv" => "fras:er:en:na"
				,"en" => "phrase:s"
				)
			,"profile:noun1" => array(
				"sv" => "profil:er"
				,"en" => "profile:s"
				)
			,"outbox:noun1" => array(
				"sv" => "skickade"
				,"en" => "outbox"
				)
			,"other:noun1" => array(
				"sv" => "annan:___dra"
				,"en" => "other:s"
				)
			,"popularity:noun1" => array(
				"sv" => "populäritet"
				,"en" => "popularity"
				)
			,"priority:noun1" => array(
				"sv" => "prioritet:er:-s"
				,"en" => "priority:_ies"
				)
			,"proposition:noun1" => array(
				"sv" => "proposition:er:en:erna"
				,"en" => "proposition:s"
				)
			,"setting:noun1" => array(
				"sv" => "inställning:ar"
				,"en" => "setting:s"
				)
			,"supporter:noun1" => array(
				"sv" => "stödjare::n:_na"
				,"en" => "supporter:s"
				)
			,"user:noun1" => array(
				"sv" => "användare"
				,"en" => "user:s"
				)
			,"time:noun1" => array(
				"sv" => "tidpunkt:er"
				,"en" => "time:s"
				)
			,"time of vote:noun1" => array(
				"sv" => "Röstningstidpunkt"
				,"en" => "Time of vote"
				)
			,"title:noun1" => array(
				"sv" => "titel"
				,"en" => "title"
				)
			,"type:noun1" => array(
				"sv" => "typ"
				,"en" => "type"
				)
			,"[your]vote:noun1" => array(
				"sv" => "röst:er:en:erna"
				,"en" => "vote:s"
				)
			,"vote:noun1" => array(
				"sv" => "omröstning:ar:en:arna:-s"
				,"en" => "vote:s"
				)
			,"vote time:noun1" => array(
				"sv" => "omröstningstid:er:en:erna"
				,"en" => "vote time:s"
				)
			,"vote admin:noun1" => array(
				"sv" => "valadministratör:er"
				,"en" => "vote admin:s"
				)
			,"vote's:noun1" => array(
				"sv" => "omröstnings"
				,"en" => "vote's"
				)
			,"voter:noun1" => array(
				"sv" => "röstande"
				,"en" => "voter"
				)
			,"workgroup:noun1" => array(
				"sv" => "arbetsgrupp:er:en:na"
				,"en" => "workgroup:s"
				)

			//NOUNS, variation 2
			,"alternative:noun2" => array(
				"sv" => "alternativ::et:en"
				,"en" => "alternative:s"
				)
			,"candidate election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "candidate election:s"
				)
			,"election:noun2" => array(
				"sv" => "personval::et:en"
				,"en" => "election:s"
				)
			,"forum:noun2" => array(
				"sv" => "forum::-"
				,"en" => "forum:s"
				)
			,"membership:noun2" => array(
				"sv" => "medlemskap"
				,"en" => "membership"
				)
			,"message:noun2" => array(
				"sv" => "meddelande:n"
				,"en" => "message:s"
				)
			,"name:noun2" => array(
				"sv" => "namn::et:en"
				,"en" => "name:s"
				)
			,"password:noun2" => array(
				"sv" => "lösenord"
				,"en" => "password:s"
				)
			,"post:noun2" => array(
				"sv" => "inlägg::et:en"
				,"en" => "post:s"
				)
			,"proposal:noun2" => array(
				"sv" => "förslag::et:en"
				,"en" => "proposal:s"
				)
			,"support:noun2" => array(
				"sv" => "stöd"
				,"en" => "support"
				)
			,"username:noun2" => array(
				"sv" => "användarnamn"
				,"en" => "username:s"
				)
			,"value:noun2" => array(
				"sv" => "värde"
				,"en" => "value"
				)
		);
	}	
} 
?>
